### ISSUE TITLE
Custom Enchanted Book

### ISSUE THREAD

**Issue by AffanStarPure** [DaPigGuy/PiggyCustomEnchants#10]
Do You Will Add Ce Book?

**Comment by daniktheboss** [comment]
Aericio are you stupid?

**Comment by EpicDF** [comment]
lol salt in github, that's a first

**Comment by daniktheboss** [comment]
Are you stupid too? Aericio isn't even a dev... smh

**Comment by DaPigGuy** [comment]
This has been added to the Todo list.
