### ISSUE TITLE
Option to disable unwanted enchants entirely

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#101]
Just a suggestion.
Piggy have many tasks, you could add a config to disable tasks/enchants that u don't use ...
Or don't plan to ever use. 
---------------------------
this will help users who experience high loads to optimize the plugin.

For example, wen I update piggy, I need to remove some tasks before using the plugin.

**Comment by QuiverlyRivalry** [comment]
Just add a random letter in a task in the code, and it breaks everything

**Comment by Aericio** [comment]
In other words, disable certain enchants that are not needed.

**Comment by DaPigGuy** [comment]
Ignore that... Was a mistake

**Comment by Aericio** [comment]
If you want to disable a certain enchantment, consider using this plugin for the time being:
https://github.com/JackMD/EnchantmentsDisabler
