### ISSUE TITLE
Cant overwrite item

### ISSUE THREAD

**Issue by MSG100TC** [DaPigGuy/PiggyCustomEnchants#102]
Please make sure your issue complies with these guidelines:
- * [yes ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [yes] Issue must have not been reported previously
- * [yes] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [yes ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [yes] If possible, provide crashdumps/errors related to the issue.

#### **General**

Plugin crashed
#### **Version of PiggyCustomEnchants:**

latest
#### **Steps to Reproduce the Issue**

1. Install and load the plugin (No error)
2. Reload the server (An error comes up)

#### **Extra Information**

Error:
"Trying to overwrite an already registered item" (EXCEPTION) In "src/pocketmine/item/ItemFactory at line 227"

PS: I can't put the whole error message here because Im hosting the server on  Windows and it doesn't allow me to copy and pastethe console.

**Comment by QuiverlyRivalry** [comment]
Blame teaspoon

**Comment by DaPigGuy** [comment]
The template literally says not to put latest 🤦‍♂️ Also, you can't be on the latest because this was already fixed...
