### ISSUE TITLE
What are the permissions of the plugin?

### ISSUE THREAD

**Issue by inaughtysteve** [DaPigGuy/PiggyCustomEnchants#103]
What are the permissions of the plugin?

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/plugin.yml

**Comment by inaughtysteve** [comment]
Thanks

**Comment by DaPigGuy** [comment]
To add on to what Aericio said, there is also an override check permission node ```piggycustomenchants.overridecheck```. Unlike ```piggycustomenchants.command.ce.enchant``` which is given to ops by default, this permission node isn't and you'll need to use a permissions plugin to give this permission node. It lets you override enchantment checks like max level & item support.
