### ISSUE TITLE
Hallucation problem!

### ISSUE THREAD

**Issue by optimusprime338** [DaPigGuy/PiggyCustomEnchants#106]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

![image](https://user-images.githubusercontent.com/27479208/34547599-4f430fde-f122-11e7-84ae-7edf73ca5df2.png)

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Try the latest build.

**Comment by optimusprime338** [comment]
ty
