### ISSUE TITLE
Transmog Scroll (New Item)

### ISSUE THREAD

**Issue by HysteriaDev** [DaPigGuy/PiggyCustomEnchants#109]
Hello Devs. Today I have a idea that's called a Transmog Scroll. What a Transmog scroll does is that by the name of the weapon, tool, armour, etc it will show a number. The number is there because of how many enchants are on the thing. Also another thing a Transmog Scroll does is list the enchantment by rarity and color. Basically if I have a gold enchant text name, all gold text will be together. And the Transmog scroll item I would like to be is a map. Thank you for reading this.

Regards -BarnesDev

**Comment by Aericio** [comment]
From what I understand, the Transmog Scroll gives each item a number based on the rarity and number of enchants on the item. (I don't see the reason for this, please explain.)

It also lists each enchantment based on their rarity, therefore color, like a manual? I don't know how you would be doing this with a map... using a book for this would be better. As far as I know, you can't show the icon of a map and have it open a book interface. (maybe possible with that new UI thing, though.)

I'm just trying to understand what you are suggesting. Please correct me if I said anything incorrect.

**Comment by BigDGucciPvP** [comment]
What he's trying to say is the Transmog Scroll will organize the enchants. @Aericio I do agree the scroll could be a book. It would most like be better than a map. I think he's trying to say is when you apply the scroll The list of enchants in the lore with organize the color/enchant rarity. I don't know if this helped at all but yeah i tried to explain.

**Comment by Muqsit** [comment]
Here's another explanation. (Source: https://wiki.cosmicpvp.com/wiki/Scrolls#Transmog_Scrolls)

When you combine a transmog scroll on to an equipment, it sorts the enchantment lores by enchantment rarity in descending order (the rarest enchantments are on top and the common ones are at the bottom, usually rarity is represented using "Simple", "Uncommon" or "Unique", "Rare" or "Elite", "UltraRare" or "Ultimate", "Legendary").

This of course means it depends upon a whole separate rarity implementation (see https://github.com/DaPigGuy/PiggyCustomEnchants/issues/2).

Any enchantments added onto the item after applying transmog scroll will NOT be sorted, rather the enchantment's lore will be added at the top or the bottom of the item's lore.

**Comment by haKingdomsCraft** [comment]
Lol Musqit Tell @Aercio What mean Transmog scroll

**Comment by DuooIncc** [comment]
This is done on the java edition however.
