### ISSUE TITLE
title is the topic.

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyCustomEnchants#11]
QuiverlyRivalry commented a minute ago
Hi, I am an Owner of a server and YOU ARE INCREDIBLY GOOD at making plugins it's astounding :1st_place_medal:
I just would like to say maybe in a future update there should be a way to buy Enchants for example /buy berserker 5 and you bought the enchant that would be awesome for my server!
Keep up the good work guys 👍
And please help make this plugin happen please :) thanks and in sorry if this isn't where u post ideas I'm new to github :P

**Comment by DaPigGuy** [comment]
What's your server? PS Aericio be nice!

**Comment by QuiverlyRivalry** [comment]
Omg u responded lol
My IP is 
galaxype.crafted.pro 26211
I'm thinking if switching to VPS soon btw :3
So I can get a dedicated server :3

**Comment by QuiverlyRivalry** [comment]
PS do you have Kik? Sorry for spamming the comment area I'm just so pumped xD

**Comment by DaPigGuy** [comment]
@QuiverlyRivalry I'm on.

**Comment by QuiverlyRivalry** [comment]
Oh see u there? Sorry I wasn't there to see ur email :P

**Comment by QuiverlyRivalry** [comment]
HI PIG PLEASE CHECK MY SERVER THANKS PIG
