### ISSUE TITLE
Second run 

### ISSUE THREAD

**Issue by ElementalMinecraftGaming** [DaPigGuy/PiggyCustomEnchants#112]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must not have been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

I was running this on my server when I noticed that it wouldn't run a second time because of file overwrite. Please fix this

#### **Version of PiggyCustomEnchants:**

 1.1.0 for ALPHA-10

#### **Steps to Reproduce the Issue**

1. nothing would work so i have to keep deleting the folder so it will run but I need it to not need this

#### **Extra Information**

  This is a good plugin when i don't have to delete files

**Comment by Aericio** [comment]
Please be more specific or we cannot help you. We don't know what is wrong unless you provide us with information (crashdumps, errors, etc.)

**Comment by Aericio** [comment]
Issue past allocated time, closing the issue now.
