### ISSUE TITLE
Question about the "give" command

### ISSUE THREAD

**Issue by Alderander** [DaPigGuy/PiggyCustomEnchants#113]
Hi. Is it possible to give enchanted items with the "give" command (?), because in my case, it return an empty item, no matter if I give an ID number or a name. If yes, how? It would be very useful for quests given by npc.

--------------------------------------------------------------------------

Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Yes, it is possible with the ID. However, due to the custom enchants not being implemented in vanilla minecraft, the enchant(s) will not show up, but will function.

**Comment by Alderander** [comment]
Fact that I did not check whether it works, thanks for the answer.
