### ISSUE TITLE
lumberjack doesnt work

### ISSUE THREAD

**Issue by llronaldoll** [DaPigGuy/PiggyCustomEnchants#115]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

lumberjack is not working, with an enchanted man is only breaking a block of the tree

#### **Version of PiggyCustomEnchants:**
 version 1.1.0

#### **Steps to Reproduce the Issue**

enchant one axe and use
1.

**Comment by DaPigGuy** [comment]
Make sure that you are sneaking.

**Comment by llronaldoll** [comment]
sorry, 
I did not know you need to sneak

**Comment by DaPigGuy** [comment]
It's fine
