### ISSUE TITLE
All the enchants etc work fine, just my cmd is spammed with [18:42:56] [Server thread/CRITICAL]: Could not execute task PiggyCustomEnchants\Tasks\PoisonousGasTask: Call to undefined method pocketmine\Player::getArmorInventory() [18:42:56] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getArmorInventory()" (EXCEPTION) in "PiggyCustomEnchants (2).phar/src/PiggyCustomEnchants/Tasks/PoisonousGasTask" at line 36

### ISSUE THREAD

**Issue by QLuch** [DaPigGuy/PiggyCustomEnchants#117]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Outdated PMMP version. The last 2 builds only work with latest due to the armor inventory split. Blame dktapps
