### ISSUE TITLE
Duplication Error

### ISSUE THREAD

**Issue by QLuch** [DaPigGuy/PiggyCustomEnchants#118]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Ive been having a problem, the tasks dont seem to work and spam cmd with the error. players when they die drop items but dont loose them therfor duplicating. please help.

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Please post the errors.

**Comment by Aericio** [comment]
@QLuch Title is not for writing the whole issue, that belongs in the General section where you explain what is wrong. Title is simply to summarize your issues. This is just a warning, please don't do it again. We also need you to fill out the issue description, or else we cannot help you.
