### ISSUE TITLE
Cripple Slowness Flying Not Working

### ISSUE THREAD

**Issue by Haxley** [DaPigGuy/PiggyCustomEnchants#119]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
1.7 dev-516
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Cripple slowness doesn't seem to work if the enemy is flying. Have not tested other enchantments slowness effects, but I have a feeling flying cancels all slowness.

#### **Version of PiggyCustomEnchants:**

1.1.0
#### **Steps to Reproduce the Issue**

1. Enchant sword with Cripple
2. Attack flying person
3. Notice their speed is not reduced

**Comment by DaPigGuy** [comment]
Slowness is handled by PMMP...

**Comment by Haxley** [comment]
Thanks
