### ISSUE TITLE
Pigs won't spawn when PiggyCE is installed with PureEntitiesX

### ISSUE THREAD

**Issue by 95CivicSi** [DaPigGuy/PiggyCustomEnchants#120]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

When PiggyCE is installed alongside PureEntitiesX, pigs will not spawn automatically, with spawn eggs, or using commands.  They appear momentarily and then disappear.

#### **Version of PiggyCustomEnchants:**

1.1.0
#### **Steps to Reproduce the Issue**

1. Create PocketMine-MP server from https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-516
2. Install PiggyCE v 1.1.0 from Poggit
3. Install PureEntitiesX v0.2.8-3.dev3 from Poggit.
4.  Attempt to spawn a Pig using /pesummon pig or a Spawn Egg

#### **Extra Information**

PiggyCE v1.1.1 has similar issues.  The issues may be different based on which version of PocketMine-MP is being used.  I'll include more info later.

**Comment by DaPigGuy** [comment]
@Aericio This is a valid issue.
