### ISSUE TITLE
Grow Allows Glitch Through Blocks Upwards

### ISSUE THREAD

**Issue by Haxley** [DaPigGuy/PiggyCustomEnchants#121]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
1.7 dev-516
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Grow allows you to glitch through blocks upwards, infinitely if you can survive suffocation. 

#### **Version of PiggyCustomEnchants:**

1.1.0
#### **Steps to Reproduce the Issue**

1. Enchant armor with Grow
2. Move forwards and upwards against a ceiling while toggling grow
3. Notice yourself pass through blocks upward with almost every toggle. 
#### **Extra Information**

I haven't been able to reproduce glitch moving downward.

**Comment by DaPigGuy** [comment]
The issue is with the client. As for suffocation, that's PMMP issue.

**Comment by Haxley** [comment]
Not saying suffocation is issue. Saying Grow allows you to pass through blocks by changing size. What do you mean by, 'issue with the client'?

**Comment by DaPigGuy** [comment]
The client's POV does not update with player size.
