### ISSUE TITLE
Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported

### ISSUE THREAD

**Issue by herojhjhLB** [DaPigGuy/PiggyCustomEnchants#125]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [X] If possible, provide crashdumps/errors related to the issue.

#### **General**

Unhandled exception executing command 'ce enchant lifesteal 1' in customenchant: Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported
[11:39:07] [Server thread/CRITICAL]: RuntimeException: "Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported" (EXCEPTION) in "vendor/pocketmine/pocketmine-nbt/src/tag/NoDynamicFieldsTrait" at line 29

#### **Version of PiggyCustomEnchants:**

latest

#### **Steps to Reproduce the Issue**

1. Dynamic field

#### **Extra Information**

Dynamic Field is no longer supported

**Comment by DaPigGuy** [comment]
Forgot to close.
