### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by shabazshah7** [DaPigGuy/PiggyCustomEnchants#127]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
Hey i download this and it says its a plugin but won't work in game i have lastest api too

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
Are you sure the plugin is in the /plugins/ folder?

**Comment by artulloss** [comment]
Same issue here
