### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shabazshah7** [DaPigGuy/PiggyCustomEnchants#128]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
I have the latest version installed and my api is 3.0.0 but still, when I do /ce or /ce help doesn't work

#### **Version of PiggyCustomEnchants:**
1.1.2

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
What do you mean by "doesn't work"? What isn't working?

**Comment by shabazshah7** [comment]
the plugin

**Comment by DaPigGuy** [comment]
🤦‍♂️

**Comment by shabazshah7** [comment]
ok... what?? just tell me please

**Comment by shabazshah7** [comment]
..
