### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by shabazshah7** [DaPigGuy/PiggyCustomEnchants#129]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
so i've installed the plugin my api is 3.0.0 and when i try use plugin says unknown command

#### **Version of PiggyCustomEnchants:**
1.1.2

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
Please stop creating issues. If you require help with installation, join our discord server. discord.gg/ZZewRQH
