### ISSUE TITLE
Will this plugin support anything other then pmmp 1 day?

### ISSUE THREAD

**Issue by Pitstopers** [DaPigGuy/PiggyCustomEnchants#13]
By that I mean well this plugin support tesseract or bluelight and etc. I'm just wondering because Half of the Community uses tesseract and bluelight .esc will this be possible one day

**Comment by QuiverlyRivalry** [comment]
Course , as you know pocketmine is dying now. and is being beaten by it's
spoons, and you have to watch out for Nukkit as well :P

**Comment by Pitstopers** [comment]
So DaPigGuy will be it I really want it for bluelight

**Comment by QuiverlyRivalry** [comment]
I'm not dapigguy btw :P

**Comment by QuiverlyRivalry** [comment]
Im a stranger :3 xD

**Comment by Pitstopers** [comment]
Ik but will he do it tho

**Comment by QuiverlyRivalry** [comment]
Idk ? Maybe or maybe not

**Comment by DaPigGuy** [comment]
Yes, if the spoons update their api.

**Comment by Pitstopers** [comment]
They did I think bluelight did

**Comment by Pitstopers** [comment]
What do you mean by update there API
