### ISSUE TITLE
Levels broken

### ISSUE THREAD

**Issue by brexmania123** [DaPigGuy/PiggyCustomEnchants#130]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
so i was using the enchants when i heard that you can go infinite levels. i tested it and its true

#### **Version of PiggyCustomEnchants:**
says i am running version 1.1.1

#### **Steps to Reproduce the Issue**

1. do normal command
2. for the level you can pick anything
3. done

**Comment by DaPigGuy** [comment]
There are checks against this. However, if you have the permission node ```piggycustomenchants.overridecheck```, the checks will not apply.

**Comment by brexmania123** [comment]
ohh ok might be since i am opped on the server
