### ISSUE TITLE
cant enchant

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#131]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

cant enchant
#### **Version of PiggyCustomEnchants:**

PiggyCustomEnchants version 1.1.2
[21:46:50] [Server thread/INFO]: Author: DaPigGuy
.

#### **Steps to Reproduce the Issue**

1. enchant something

#### **Extra Information**

[Server thread/CRITICAL]: Unhandled exception executing command 'ce enchant volley 3 aster' in customenchant: Call to undefined method pocketmine\nbt\tag\ListTag::push()
[21:43:26] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\nbt\tag\ListTag::push()" (EXCEPTION) in "PiggyCustomEnchants-master/src/PiggyCustomEnchants/Main" at line 502

**Comment by TDMidkwhatisxd** [comment]
pmmp version       implementing API version 3.0.0-ALPHA11 for Minecraft: PE v1.2.10 (protocol version 201)erver thread/INFO]: This server is running PocketMine-MP 1.7dev-743 ▒[REDACTED]▒

**Comment by DaPigGuy** [comment]
Outdated PMMP build.

**Comment by xXNiceAssasinl0** [comment]
Use https://github.com/pmmp/PocketMine-MP/releases don’t use not release @TDMidkwhatisxd

**Comment by TDMidkwhatisxd** [comment]
https://github.com/pmmp/PocketMine-MP/releases
Are you guys blind, or don't even bother to read? Check latest release build, I use it.

**Comment by TDMidkwhatisxd** [comment]
PocketMine-MP 1.7dev-743  is latest release

**Comment by Aericio** [comment]
Sorry for the misunderstanding. Since 743, there have been some nbt tag modifications. You should be using the latest build provided by **Jenkins**, not the releases in GitHub. If you want to use the latest stable release, then use an older version of PiggyCE. (versions before 1.1.2)

Link: https://jenkins.pmmp.io/job/PocketMine-MP/791/
