### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by shabazshah7** [DaPigGuy/PiggyCustomEnchants#133]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
I installed your plugin v.1.1.2 and  my API is This server is running PocketMine-MP [#63fa6a3 2018-02-08] 1.7dev 「[REDACTED]」 implementing API version 3.0.0-ALPHA11 for Minecraft: PE v1.2.10 (protocol version 201) and it says it is installed and but commands for plugin don't work

#### **Version of PiggyCustomEnchants:**
1.1.2

#### **Steps to Reproduce the Issue**
1.Reinstalled

**Comment by DaPigGuy** [comment]
Stop spamming.
