### ISSUE TITLE
Plugin does not work on VirtualGladiators

### ISSUE THREAD

**Issue by dev4uhelp** [DaPigGuy/PiggyCustomEnchants#134]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
Tried your plugin on 2 different hosts both pocketmine and your plugin doesnt work on virtual gladiators but works on a different host API is same too

#### **Version of PiggyCustomEnchants:**
1.1.2

#### **Steps to Reproduce the Issue**
1.

**Comment by DaPigGuy** [comment]
Can you provide more information? Versions of PMMP? What build of PiggyCE? What isn't working?

**Comment by Aericio** [comment]
If I am not mistaken, you cannot upload your own server software onto Virtual Gladiators, you can only select from the ones that are listed. It is possible that they have an older version of PMMP available, since it works on another host. Contact Virtual Gladiators support instead to ask them to update their PMMP phar.

**Comment by dev4uhelp** [comment]
so I downloaded piggycustomenchants v1.1.2 and my phar is the latest as I have just downloaded it a day ago from their official web ... it says it's enabled but it won't let me do anything for the plugin e.g /ce help or /ce list or /ce enchant just says unknown command

**Comment by brexmania123** [comment]
Aericio, as someone who has used VG i know that you can upload custom plugins and stuff. At the time i wasnt actually part of the dev team, but the server did have a custom core and the owner uploaded his own plugins

**Comment by helloitsmenab** [comment]
same with me I use Virtual Gladiators, the piggycustomenchants plugin doesn't work for meee too but works on my other server my phar is latest and piggy 1.1.2

**Comment by brexmania123** [comment]
i noticed that the 2 latest phars are actually broken
so use build 209 which is the latest released phar that is not beta.

**Comment by helloitsmenab** [comment]
im using PocketMine-MP 1.7dev-743 with API 3.0.0-ALPHA11

**Comment by dev4uhelp** [comment]
I'm using that too

**Comment by brexmania123** [comment]
no, i mean for the plugin not Pocketmine

**Comment by dev4uhelp** [comment]
yh ur right

**Comment by DaPigGuy** [comment]
The last 2 builds will only support PMMP builds after the NBT changes.

**Comment by DaPigGuy** [comment]
You can get the latest PMMP build here: https://jenkins.pmmp.io/job/PocketMine-MP/

**Comment by dev4uhelp** [comment]
i am using pmmp

**Comment by Aericio** [comment]
Use the latest version of PMMP **and** the latest version of PiggyCustomEnchants.

**Comment by dev4uhelp** [comment]
yes I am ... on ramshard i successfully installed it but on virtual gladiators it doesn't work  both r pocketmine

**Comment by Aericio** [comment]
If it works on RAMShard and not VG, then it's not our problem.

**Comment by dev4uhelp** [comment]
btw when will you fix /enchant
