### ISSUE TITLE
Cant enchant

### ISSUE THREAD

**Issue by dev4uhelp** [DaPigGuy/PiggyCustomEnchants#135]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
it wont let me enchant piggy v 1.1.2 and pmmp_698_1.2.10.phar

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Next issue and you're banned. Stop spamming.
