### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by helloitsmenab** [DaPigGuy/PiggyCustomEnchants#136]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
 keep getting errors in console didnt happen before i installed plugin

#### **Version of PiggyCustomEnchants:**
 1.1.2

#### **Steps to Reproduce the Issue**

1. redownload piggyces and phar

#### **Extra Information**

![screenshot 2018-03-08 at 7 43 36 pm](https://user-images.githubusercontent.com/36928712/37173125-a50d57c0-230a-11e8-9cd5-f8be53884390.png)

**Comment by DaPigGuy** [comment]
The last 2 builds of PiggyCE require the PMMP builds after the NBT changes
