### ISSUE TITLE
Soulbound drops extra item

### ISSUE THREAD

**Issue by ArceusMatt** [DaPigGuy/PiggyCustomEnchants#138]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Applying soulbound to any item then dying dupes the item,
A player can simply use /back or /home to get the duped item.
I am pretty sure soulbound is only suppose to allow the user to keep their item?
I was hoping you could make sure they don't drop the item if they have soulbound.

#### **Version of PiggyCustomEnchants:**

1.1.2

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
What plugin are you using for /back or /home? I'll try to reproduce that part of the issue.
Believe the other part of that had been reported before... I thought it was fixed @DaPigGuy?

**Comment by ArceusMatt** [comment]
The /back & /home command plugin name doesn't really matter as it's not apart of the pure issue.
(I only mentioned those for the description of my problem)
/back & /home is only used to get the item they dropped.
If you still need to know the names (which don't really take part in the bug because they could basically walk up to the extra dropped item & pick it up)
- essentialsTP
- EssentialsPE

**Comment by Aericio** [comment]
Ahh, thought you meant that using those commands would dupe the items.

**Comment by ArceusMatt** [comment]
I updated & this issue seems to be fixed.
