### ISSUE TITLE
TEST SERVER - JOIN OR PIGGY WILL HAUNT YOU

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyCustomEnchants#14]
If you want to see how PiggyCustomEnchants works and how great the handsome piggy @DaPigGuy and nooby @Aericio are,  you can try the plugin on my server.

**IP**: galaxype.crafted.pro
**Port**: 26211

Long live Piggies!  

PS I will be changing the IP soon. Credits to @DaPigGuy for the plugin!

>Piggy is everywhere.

**Comment by QuiverlyRivalry** [comment]
Lol

**Comment by QuiverlyRivalry** [comment]
Yo wanna meet on server lmao?

**Comment by DaPigGuy** [comment]
Ok. PS I changed it to a slightly more formal tone. 😛

**Comment by QuiverlyRivalry** [comment]
LMAO xD kk I'm be there

**Comment by QuiverlyRivalry** [comment]
I'm rn there :D
