### ISSUE TITLE
/ce enchant does not enchant

### ISSUE THREAD

**Issue by ArceusMatt** [DaPigGuy/PiggyCustomEnchants#140]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

16.03 00:06:32 [Server] Server thread/CRITICAL Unhandled exception executing command 'ce enchant soulbound 1' in customenchant: Call to undefined method pocketmine\nbt\tag\ListTag::push()
16.03 00:06:32 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\nbt\tag\ListTag::push()" (EXCEPTION) in "PiggyCustomEnchants/src/PiggyCustomEnchants/Main" at line 502

#### **Version:**

- PiggyCustomEnchants: 1.1.2

- PMMP: 1.7dev-743

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

This happens to all enchantments that ive used so far, basically it says "unknown error" in game & doesn't enchant. But in console the error i provided happens.

**Comment by ArceusMatt** [comment]
So my PMMP is outdated?

**Comment by DaPigGuy** [comment]
Outdated PMMP  build, yes. The last 3 builds of PiggyCE are only for recent PMMP builds.

**Comment by ArceusMatt** [comment]
I can confirm you're right, i just updated & it seems my other issue is fixed aswell.
I will close my other issue.
