### ISSUE TITLE
Duping with Private Vault

### ISSUE THREAD

**Issue by isoz** [DaPigGuy/PiggyCustomEnchants#150]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

If I put a sword in my private vault by muqsit and then move an enchanted book to it with an enchant that it already has it will give me a copy of that sword in my inventory.

#### **Version:**

PiggyCustomEnchants version 1.1.2

This server is running PocketMine-MP 1.7dev for Minecraft: PE [REDACTED] (protocol version 3.0.0-ALPHA11)

#### **Steps to Reproduce the Issue**

1. /give iso 403 1 {display:{Name:"§r§6Blessed 3 Enchant§r"},ench:[{id:120s,lvl:3s}]}
2. Move sword to a random slot in pv
3. Drag book to sword
4. A new sword appears in inventory

Remember the sword has to have the Blessed enchant already on it.

#### **Extra Information**

I reported this previously in the Private Vaults plugin and @Muqsit suggested I post an issue here regarding disabling the function in container inventories and also provided a video with it in action, at the end you can see with Piggy enabled it dupes the sword. https://streamable.com/90900

**Comment by isoz** [comment]
Anyone?

**Comment by Aericio** [comment]
told piggy, he said he will look at it later.

**Comment by isoz** [comment]
Sorry to bother again but this is kinda important to me.

**Comment by Muqsit** [comment]
This does happen on a plain server (tried with Windows 10):
- Put a sword in a chest
- Drag and drop a book onto the chest

**Comment by isoz** [comment]
Thanks Muq. Appreciated.

**Comment by isoz** [comment]
While you're at it. There's another issue with the books, not sure if this is strictly PMMP or not but when they have the same name they stack and can't be unstacked, moved.

**Comment by Muqsit** [comment]
@isoz That's mojang's actually. I think they allowed stacked books at one point but recently made them unstackable. Whatever it is, registering a custom EnchantedBook item class with `getMaxStackSize()` returning `1` should fix it.
