### ISSUE TITLE
CustomEnchantShop problem

### ISSUE THREAD

**Issue by Scali3n** [DaPigGuy/PiggyCustomEnchants#153]
Hello, I recognize your talent for development but I have a slight problem, voila when I try to add a shop in the tone Plugin CustomEnchantShop nothing happens yet I do the command / ceshop add, it opens me the window of sale I configure my sale but it does not add, thank you for helping me, and excuse me for my bad english I'm french x) (yes your plugin is known throughout the world :-p) thanks you :)

**Comment by Aericio** [comment]
So, `/ceshop add` doesn't add to the list?

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyCustomEnchantsShop/issues/12
