### ISSUE TITLE
How to use combiner and Enchantment book doesn’t register

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [DaPigGuy/PiggyCustomEnchants#156]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [unknown] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [wat] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [nu] If possible, provide crashdumps/errors related to the issue.

#### **General**

Enchantment book doesn’t Register how do I use combier

#### **Version:**

- PiggyCustomEnchants: 1.1.3

- PMMP: 937

#### **Steps to Reproduce the Issue**

1. Just put plugin load

#### **Extra Information**

How do I use combiner xd

**Comment by DaPigGuy** [comment]
You enchant a normal book with an enchant. You then put your item on top of your enchanted book in your inventory.

**Comment by xXNiceAssasinl0** [comment]
Like wat enchantment
