### ISSUE TITLE
How To Configure so I can have custome enchants on advancedkits??

### ISSUE THREAD

**Issue by WarKnight1** [DaPigGuy/PiggyCustomEnchants#158]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

I would like to know how i can put custom enchants on advanced kits..

**Comment by Aericio** [comment]
AdvancedKits already added support for PiggyCE.
