### ISSUE TITLE
perms enhancemets

### ISSUE THREAD

**Issue by optimusprime338** [DaPigGuy/PiggyCustomEnchants#16]
Can you add perms for each type of enchant players can do . that would be awesome for ur to
manage it!!!!!
Thanks

**Comment by QuiverlyRivalry** [comment]
Just a suggestion do you mean like players need perms to run a custom enchant? 
I know a plugin which I use on my server galaxype.crafted.pro which makes you have to pay to run a custom enchant eg
./buycmd charge
Console will do /ce enchant charge {player} 1

**Comment by QuiverlyRivalry** [comment]
Would you like the plugin name?

**Comment by optimusprime338** [comment]
Yes please!!

**Comment by QuiverlyRivalry** [comment]
The plugin name is Command shop by @BoxOfDevs 
Make sure you also credit @DaPiggyGuy for the awesome Custom Enchants :) It's the only one out there

**Comment by QuiverlyRivalry** [comment]
*@DaPigGut

**Comment by QuiverlyRivalry** [comment]
Ahh i can't spell @DaPigGuy

**Comment by optimusprime338** [comment]
will do, thanks so much:)
