### ISSUE TITLE
not working on latest pmmp

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#161]
[Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\item\enchantment\Enchantment::__construct(), 5 passed in /root/plugins/PiggyCustomEnchants-master/src/PiggyCustomEnchants/Main.php on line 425 and exactly 6 expected" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 170

**Comment by TDMidkwhatisxd** [comment]
is easy to fix ... :)

**Comment by DaPigGuy** [comment]
This has already been fixed. Outdated version of PiggyCE.

**Comment by TDMidkwhatisxd** [comment]
you right, thanks
