### ISSUE TITLE
Jetpack

### ISSUE THREAD

**Issue by isoz** [DaPigGuy/PiggyCustomEnchants#162]
Jetpack doesn't seem to be working properly, the power bar doesn't change and players don't lose speed overtime.

What variable can I change in the code to reduce jetpack speed?

**Comment by DaPigGuy** [comment]
Please use the default issue template. As for the issue, it will be looked into. 



To reduce the jetpack speed, you can multiple the level variable by a number under 1 [here](https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/src/PiggyCustomEnchants/Tasks/JetpackTask.php#L81). For example, $level * 0.75 will be 75% of the normal speed.

**Comment by DaPigGuy** [comment]
The power bar decreases as normal. You can change the amount of time you can fly with jetpack [here](https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/src/PiggyCustomEnchants/EventListener.php#L1311)

**Comment by isoz** [comment]
It does not decrease in my server using PocketMine-MP 1.7dev 「[REDACTED]」 implementing API version 3.0.0-ALPHA12 for Minecraft: PE v1.4.0 (protocol version 261)

It just stays maxed and green the whole time, if I fly up it pushes me down a few seconds later but the bar does not change neither the speed.

**Comment by DaPigGuy** [comment]
Each ▌should represent 15 seconds, with 20 ▌at the start, for 300 seconds or 5 minutes

**Comment by DaPigGuy** [comment]
The speed does not decrease as power decreases. Jetpack Speed is only affected by the enchantment level.

**Comment by ComboLordC** [comment]
Can u send me the phar for custom enchsnts bc the one I go from you is
outdated

**Comment by DaPigGuy** [comment]
@ComboLordC https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants/PiggyCustomEnchants

**Comment by ComboLordC** [comment]
So how do I download it

**Comment by ComboLordC** [comment]
And btw in in version 1.4

**Comment by ComboLordC** [comment]
It's outdated I'm not on version 1.1.1

**Comment by DaPigGuy** [comment]
https://poggit.pmmp.io/r/30609/PiggyCustomEnchants_dev-228.phar

**Comment by ComboLordC** [comment]
Broooo thx alot aye can u do me a favor and send me alot phar need for a
face server

**Comment by ComboLordC** [comment]
Meant faction

**Comment by ComboLordC** [comment]
Are can u send me the phar For Kits,Slappers,Pureperms

**Comment by Aericio** [comment]
If you want to setup your own server, you should be getting the plugins yourself. We are not a server setup hotline. Most plugins can be found at https://poggit.pmmp.io/.
