### ISSUE TITLE
Molten Task

### ISSUE THREAD

**Issue by IonicSyz1823** [DaPigGuy/PiggyCustomEnchants#168]
12.06 11:01:52 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'PiggyCustomEnchants v1.1.3': Class 'PiggyCustomEnchants\Tasks\MoltenTask' not found on PiggyCustomEnchants\EventListener
12.06 11:01:52 [Server] Server thread/CRITICAL Error: "Class 'PiggyCustomEnchants\Tasks\MoltenTask' not found" (EXCEPTION) in "DevTools/src/PiggyCustomEnchants/EventListener" at line 1073
12.06 11:01:52 [Server] Server thread/DEBUG #0 DevTools/src/PiggyCustomEnchants/EventListener(154): PiggyCustomEnchants\EventListener->checkArmorEnchants(pocketmine\Player object, pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(38): PiggyCustomEnchants\EventListener->onDamage(pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(PiggyCustomEnchants\EventListener object, pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(701): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Entity(890): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #5 src/pocketmine/entity/Living(528): pocketmine\entity\Entity->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #6 src/pocketmine/Player(3704): pocketmine\entity\Living->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #7 src/pocketmine/Player(2514): pocketmine\Player->attack(pocketmine\event\entity\EntityDamageByEntityEvent object)
12.06 11:01:52 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(132): pocketmine\Player->handleInventoryTransaction(CortexPE\network\InventoryTransactionPacket object)
12.06 11:01:52 [Server] Server thread/DEBUG #9 TeaSpoon_dev-198 (1).phar/src/CortexPE/network/InventoryTransactionPacket(155): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(CortexPE\network\InventoryTransactionPacket object)
12.06 11:01:52 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): CortexPE\network\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
12.06 11:01:52 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(CortexPE\network\InventoryTransactionPacket object)
12.06 11:01:52 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
12.06 11:01:52 [Server] Server thread/DEBUG #13 src/pocketmine/Player(3033): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
12.06 11:01:52 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/RakLibInterface(158): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
12.06 11:01:52 [Server] Server thread/DEBUG #15 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 64.237.237.35 16678, raklib\protocol\EncapsulatedPacket object, integer 0)
12.06 11:01:52 [Server] Server thread/DEBUG #16 src/pocketmine/network/mcpe/RakLibInterface(103): raklib\server\ServerHandler->handlePacket()
12.06 11:01:52 [Server] Server thread/DEBUG #17 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process()
12.06 11:01:52 [Server] Server thread/DEBUG #18 src/pocketmine/network/mcpe/RakLibInterface(80): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object)
12.06 11:01:52 [Server] Server thread/DEBUG #19 vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
12.06 11:01:52 [Server] Server thread/DEBUG #20 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
12.06 11:01:52 [Server] Server thread/DEBUG #21 src/pocketmine/Server(2279): pocketmine\snooze\SleeperHandler->sleepUntil(double 1528815712.46)
12.06 11:01:52 [Server] Server thread/DEBUG #22 src/pocketmine/Server(2150): pocketmine\Server->tickProcessor()
12.06 11:01:52 [Server] Server thread/DEBUG #23 src/pocketmine/Server(1733): pocketmine\Server->start()
12.06 11:01:52 [Server] Server thread/DEBUG #24 src/pocketmine/PocketMine(290): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
12.06 11:01:52 [Server] Server thread/DEBUG #25 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)

**Comment by DaPigGuy** [comment]
Make sure you properly installed the plugin, and make sure you did not modify the plugin (unless you know what you're doing). There is no issue, and this can't be reproduced.

**Comment by DaPigGuy** [comment]
Also make sure to use the template.
