### ISSUE TITLE
Enchantment effects won’t work but it can be applied

### ISSUE THREAD

**Issue by RyanTheOwner** [DaPigGuy/PiggyCustomEnchants#169]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1. Fix it

**Comment by DaPigGuy** [comment]
Not enough information.

**Comment by RyanTheOwner** [comment]
Are you able to come check it out on my server

**Comment by DaPigGuy** [comment]
Make sure you have the latest PMMP and PiggyCE version

**Comment by DaPigGuy** [comment]
Send IP and Port here: https://dapigguy.github.io/Contact/
