### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyCustomEnchants#17]
Hello again MrPiggy!
I have noticed that when two players are pvping with custom enchant one if the players will get there armour they are wearing duplicated and replace the current hotbar slots

**Comment by DaPigGuy** [comment]
What?...

**Comment by BrianZP** [comment]
Please elaborate more. I have been using this plugin for quiet a long time now. Idk what you are talking about.

**Comment by QuiverlyRivalry** [comment]
Okay so,
Person A is Pvping Person B
Person A is loosing, and has less health
Person B's first 4 hotbar slots get replaced by Person's A gear he's currently wearing while person Person A has is gear still on.

I'm using the Revive enchant, is it that?

**Comment by DaPigGuy** [comment]
Try without the Revive enchant

**Comment by QuiverlyRivalry** [comment]
Yep that's it :D

**Comment by QuiverlyRivalry** [comment]
A
