### ISSUE TITLE
Enchantment Bug

### ISSUE THREAD

**Issue by RyanTheOwner** [DaPigGuy/PiggyCustomEnchants#170]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants: https://poggit.pmmp.io/r/33460/PiggyCustomEnchants_dev-237.phar

- PMMP:

#### **Steps to Reproduce the Issue**

1. The enchants are unable to work, the plugin won’t load onto my server, you can apply the enchantment itself on an item but the effects of that enchantment won’t activate

**Comment by DaPigGuy** [comment]
Please provide PiggyCE and PMMP version...
