### ISSUE TITLE
Farmer Enchantment Needs Help

### ISSUE THREAD

**Issue by Haxley** [DaPigGuy/PiggyCustomEnchants#171]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Crops that use their harvested item as the seed don't play well with the farmer enchantment. You can hold down farmer hoe on a carrot or potato crop and it will essentially just dupe the item. Crops that require seeds to grow, I.e. beetroot or wheat, are not necessarily effected by this. Holding farmer hoe on these crops will mass produce their seeds, but not the end-crop. This is all to say, farmer hoe only needs a one-block-sized farm for carrots & potatoes for maximum harvesting rate. 
#### **Version:**

- PiggyCustomEnchants: 1.1.3

- PMMP: 1001

#### **Steps to Reproduce the Issue**

1. Plant potato or carrot
2. Hold farmer hoe on it
3. Observe infinite potatoes/carrots being created

#### **Extra Information**

Suggestion is to only allow farmer enchant to replant the crop if the seed exists in your inventory, then remove the seed from the inventory once planted.

**Comment by Haxley** [comment]
I think what your saying might happen if you stand directly on top of the crop, but not if you stand anywhere else. Please watch this video. In a matter of 15 seconds I was able to turn 1 potato into 20. https://cl.ly/2q453U3Y2w0Q

**Comment by DaPigGuy** [comment]
You're using Fortune.

**Comment by DaPigGuy** [comment]
Can't reproduce this issue whatsoever

**Comment by DaPigGuy** [comment]
Oh. I have reproduced the issue.

**Comment by DaPigGuy** [comment]
It will only work if you destroy a crop with a Farmer hoe without the crop in your inventory.

**Comment by Haxley** [comment]
https://cl.ly/2P0C3w0y153G

**Comment by Haxley** [comment]
Oh nice
