### ISSUE TITLE
Enchants doesn't appear slash snow

### ISSUE THREAD

**Issue by XDqrkneZ** [DaPigGuy/PiggyCustomEnchants#172]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [X] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [X] If possible, provide crashdumps/errors related to the issue.

#### **General**

I enchanted my sword then it said Enchantment succeeded. But the enchant name doesn't show in lore.
#### **Version:**

- PiggyCustomEnchants: version 1.2.0

- PMMP: PocketMine-MP 3.0.3 for Minecraft: PE v1.4.0 (protocol version 261)
#### **Steps to Reproduce the Issue**

1. hold a sword
2. /enchant player_name 104 1
3. Hover on the sword
4. You won't see "Poison I" for example in lore or something.

**Comment by DaPigGuy** [comment]
Please use /ce enchant. The default enchantment command will NOT add lore, as it is done by the client for vanilla enchantments.

**Comment by XDqrkneZ** [comment]
It uses custom names for enchants? What if I rename my item with a custom enchantment on it, it will get rid of the enchantments
