### ISSUE TITLE
Bows arrows activates slapper

### ISSUE THREAD

**Issue by MSG100TC** [DaPigGuy/PiggyCustomEnchants#175]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

How to disable that?
Using enchants:
headhunter, blaze, volley

**Comment by DaPigGuy** [comment]
Do bows normally affect Slappers?

**Comment by DaPigGuy** [comment]
This issue can not be reproduced whatsoever. Shooting a Slapper with any bow could not activate the Slapper's commands.

**Comment by MSG100TC** [comment]
Hmm, let me upload a video...
