### ISSUE TITLE
Jetpack not stopping!

### ISSUE THREAD

**Issue by Lazerplayz** [DaPigGuy/PiggyCustomEnchants#179]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

While I was testing this plugin, I seemed to stumbled into an issue, when I was testing the jetpack ce it kept and flying and flying and flying, I tried everything, I even downgraded my PMMP version and this issue still occurred 
#### **Version:**

- PiggyCustomEnchants: 1.2.0

- PMMP:3.0.7 (protocol version 274)

#### **Steps to Reproduce the Issue**

1. Download the plugin
2. Enchant your diamond boots to the Jetpack ce, and fly!

#### **Extra Information**

No, I couldn’t find any errors while I was using the plugin, the only thing close enough to an error would be the “User moved too fast, reverting movement” msg

**Comment by DaPigGuy** [comment]
You can disable the jetpack by sneaking while you are on the ground.

**Comment by Lazerplayz** [comment]
I know I can disable it while being on the floor, isn’t there a certain amount of time the jetpack can be used for?
