### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by AffanStarPure** [DaPigGuy/PiggyCustomEnchants#18]
PocketMine-MP Crash Dump Fri Jun 30 15:00:00 CEST 2017

Error: Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getId() must be compatible with pocketmine\item\enchantment\Enchantment::getId(): int
File: PiggyCustomEnchants_v1.0.1/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants
Line: 240
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[231]      */
[232]     public function setLevel($level)
[233]     {
[234]         $this->level = (int)$level;
[235] 
[236]         return $this;
[237]     }
[238] 
[239] 
[240] }
[241] 
[242] 
[243] 
[244] 
[245] 
[246] 
[247] 
[248] 
[249] 
[250] 

Backtrace:

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA6]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux fr35.server.pro 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP Version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

I tired fix this plugin... Can u fix it idk how fix again. @DaPigGuy 
I Use PMMP original

**Comment by DaPigGuy** [comment]
What branch are you using?...

**Comment by AffanStarPure** [comment]
PMMP poggit

**Comment by BrianZP** [comment]
Try using Jenkins build. And be sure to be using master branch of PocketMine-MP not api3/blocks or others as they are in development and are not at all recommended for production servers. Other than that I was not able to reproduce the error, using the latest build of both PocketMine-MP and PiggyCustomEnchants.

**Comment by PvPsaturN** [comment]
Do i have download on zip pls give me phar i dont know how to use zip

**Comment by QuiverlyRivalry** [comment]
You can use the Plugin Zip Plugin Loader ;)

**Comment by PvPsaturN** [comment]
PiggyCustomEnchants\CustomEnchants\CustomEnchants::setLevel($level) should be compatible with pocketmine\item\enchantment\Enchantment::setLevel(int $level) in phar:///storage/emulated/legacy/Genisys/plugins/CustomEnchants.phar/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants.php on line 226 help
