### ISSUE TITLE
WitherSkull Enchant does not apply Wither Effect

### ISSUE THREAD

**Issue by KrakenTheKiller** [DaPigGuy/PiggyCustomEnchants#182]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants: 1.2.0

- PMMP: 3.1.0

#### **Steps to Reproduce the Issue**

1. /ce enchant WitherSkull

#### **Extra Information**

Can you also add explosions to wither skull enchant? But anti-grief.

**Comment by Aericio** [comment]
`WitherSkull` is not a valid enchantment.

**Comment by Aericio** [comment]
My bad. An idiot named @DaPigGuy did not update the wiki.
