### ISSUE TITLE
High server load

### ISSUE THREAD

**Issue by ManiakMCPE** [DaPigGuy/PiggyCustomEnchants#183]
The plugin is causing the server to have a lower TPS even when some of the high load enchants aren't even being used.

I believe this issue started occurring after the latest 1.6 update.

https://imgur.com/5O9xORN

**Comment by Aericio** [comment]
It's not being used, but the enchantments are on the items, correct?

**Comment by Aericio** [comment]
No enchantments on any items, but plugin is loaded and one player connected: 
- timings: https://timings.pmmp.io/?id=390
- report: https://pastebin.com/60N8spQ6

Enchantments from your paste, one player connected.
- timings: https://timings.pmmp.io/?id=394
- paste: https://pastebin.com/mgdcRGB0

Unable to reproduce, but particles could be reduced (why are there so many >_<).

**Comment by ManiakMCPE** [comment]
Why is it causing so much lag in the first place? I don't use any of the insane enchants. I only allow players to have things like poison or backstab and only at levels 1 or 2.

Which enchants should I disable to reduce the high load?

**Comment by Aericio** [comment]
I don't think disabling the enchants would disable the tasks from loading. see [Main.php](https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/src/PiggyCustomEnchants/Main.php#L312-L325) 
Unless I am blind, no checks are made to see if they are necessary or not. 

What are the enchants that you are using? If none of them requires a certain task, then comment out the task (just make sure you won't use enchants needing those tasks)
