### ISSUE TITLE
Enchants do not register properly

### ISSUE THREAD

**Issue by KielKing** [DaPigGuy/PiggyCustomEnchants#184]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Plugin does not register enchants properly.
No i have not edited any code.
The only enchant that comes up on /ce list is Driller.

#### **Version:**

- PiggyCustomEnchants: 1.2.0

- PMMP: 3.2.1

#### **Steps to Reproduce the Issue**

1. Install the plugin to your server.
2. Connect to the server
3. Type /ce enchant vampire 1 *username*

**Comment by Aericio** [comment]
Issue could not be reproduced.
