### ISSUE TITLE
How to put them on crates?

### ISSUE THREAD

**Issue by Play2KillTV** [DaPigGuy/PiggyCustomEnchants#187]
Please make sure your issue complies with these guidelines:
- * [pocketmine 3.3.1 ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [no ] Issue must have not been reported previously
- * [yes ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ How can I add them on crates?] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

I dont know how to add them on crates and on advanced kits. please help me.
#### **Version:**

- PiggyCustomEnchants:1.4.1

- PMMP:3.3.1

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
read: https://github.com/luca28pet/AdvancedKits/blob/master/README.md
