### ISSUE TITLE
Pigs/Skulls etc. stay

### ISSUE THREAD

**Issue by Matthww** [DaPigGuy/PiggyCustomEnchants#189]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

As you can see in the screenshot Pigs (Porkified) witherskull etc stay.

![image](https://user-images.githubusercontent.com/3885070/50025332-77f5ef00-ffe5-11e8-9290-a1b5eff38ea2.png)

#### **Version:**

- PiggyCustomEnchants: 1.4.2

- PMMP: 3.5.1

#### **Steps to Reproduce the Issue**

1. Shoot with the Porkified or Witherskull bow

**Comment by Haxley** [comment]
How do we work around this? Persisting pigs lag everything. Combine porkified with volley and gg.

**Comment by Aericio** [comment]
I suppose I'll just comment out these enchantments.
