### ISSUE TITLE
Random enchanted books

### ISSUE THREAD

**Issue by haKingdomsCraft** [DaPigGuy/PiggyCustomEnchants#192]
Add New Thing to Enchanted Books  example MythicBook Get Random Rarity Mythic custom enchants

**Comment by DenielWorld** [comment]
This can already be done by the plugin 'BookSystem'

**Comment by ZZWILLIAMXXTrue** [comment]
DenielWorld link to ‘BookSystem’

**Comment by Aericio** [comment]
https://github.com/Aericio/BookSystem
