### ISSUE TITLE
Adding recharging the jetpack and adding to toggle off the jetpack in the air!

### ISSUE THREAD

**Issue by Wertzui123** [DaPigGuy/PiggyCustomEnchants#193]
1. Why is there no recharge Item?
2. Why can't I deaktivate the jetpack in the air?

**Comment by Aericio** [comment]
1) You need to wait 5 minutes per recharge.
2) Deactivating jetpack in air will make you fall to the ground + possibly trigger anticheat. You need to land before deactivating.

**Comment by Wertzui123** [comment]
1. Hm okey
2. Makes sense, hm :thinking:
