### ISSUE TITLE
Change info enchant from name to lore

### ISSUE THREAD

**Issue by MrDinoDuck** [DaPigGuy/PiggyCustomEnchants#194]
Why? Because when i changed item name, the ce disappear. This can fix easy by changing ce text from name to lore

**Comment by Aericio** [comment]
Now that I think about it, that would cause backwards compatibility issues... maybe not so fast.

**Comment by Aericio** [comment]
Quickly scanned, it looks like it assigns an NBT tag, so enchants should still work even if the name is changed 🤔

**Comment by Aericio** [comment]
I misread your comment, yes this can be done. I will do it eventually.
