### ISSUE TITLE
Choice to use CustomName or Lore

### ISSUE THREAD

**Issue by UnknownOre** [DaPigGuy/PiggyCustomEnchants#198]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [X] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [X] If possible, provide crashdumps/errors related to the issue.

#### **General**
The Custom Enchantment not showing in item Lore
#### **Version:**
PiggyCustomEnchants version 1.4.3
Author: DaPigGuy
- PMMP:
 PocketMine-MP 3.6.1 for Minecraft: Bedrock Edition v1.9.0 (protocol version 332

#### **Steps to Reproduce the Issue**

1. hold an item
2./ce enchant LifeSteal 1

**Comment by Aericio** [comment]
Update PMMP to 3.6.3 and try again. It is working for me.

**Comment by UnknownOre** [comment]
> Update PMMP to 3.6.3 and try again. It is working for me.

ok

**Comment by UnknownOre** [comment]
https://youtu.be/MBXS0gQ03NM on version 3.6.4

**Comment by Aericio** [comment]
You won't see it on the popup, but you will see it in the inventory. You won't get the enchant names shown there anymore because we are using lore instead, and that doesn't show on popup. I might add an option to choose whether to use custom name or lore.

**Comment by Aericio** [comment]
I haven't tested it yet, but it should work. Please tell me if there are any issues.

**Comment by ComboLordC** [comment]
Its tripping

> When i make the ce phar into a zip and edit the enchants to change the
> names or/ the rarity it doesnt work when i use an online convertor to make
> it back to a phar bc when i use the phar with the edited enchants it doesnt
> load the phar

**Comment by Aericio** [comment]
@ComboLordC Unrelated to this issue.

Also, modifying the code yourself is not my problem. If you don't know what you are doing, then don't edit the plugin. I can't provide any help either if you only say "i edit code and it doesn't work."
