### ISSUE TITLE
Todo & Suggestions

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyCustomEnchants#2]
In order to prevent our issue tracker from being clogged up by suggestions instead of errors/bugs, please post suggestions only in this issue. Current issues will be left open until completed, but future requests should only be located here. 
Be detailed about the request and state what it would help with (i.e. balancing, feature, etc.)

**Do not engage in pointless talks, or you will be banned from commenting. We've unlocked this issue to allow suggestions.**

* - [ ] Enchanting
  * - [x] Custom Enchant Books (#10, #56)
    * - [ ] Converting Enchants to Enchant Books (#72)
    * - [x] Combiner
  *  - [x] Check if item can be enchanted 
* - [ ] Enchants
  *  - [ ] Suggestions
     * - [x] #41 
       * - [x] Armored
       * - [x] Tank
       * - [x] Heavy
     * - [x] #62
       * - [x] Blessed
       * - [x] Enraged
  * - [ ] Vanilla Enchants (If not implemented fully in PMMP)
  * - [x] Enchant Rarity Colors (#6) 
* - [ ] Configuration
  * - [ ] Configuring Max Level
  * - [ ] Configuring Rarity
  * - [ ] Configuring Chances
* - [x] Commands
  * - [x] Subcommands
    * - [x] Enchant
    * - [x] List
    * - [x] About
    * - [x] Info
    * - [x] Help
    * - [x] Individual Permissions for Subcommands
  * - [x] Forms 
* - [ ] Language System
  * - [ ] Implementation
  *  - [ ] Languages
     * - [ ] English
     * - [ ] Spanish
     * - [ ] French
     * - [ ] Russian
     * - [ ] Chinese
* - [x] API
  * - [x] Adding Enchants
  * - [x] Removing Enchants
  * - [x] Registering Enchants

**Comment by moneymill2400** [comment]
How do I put this on my server I will give you credit

**Comment by MCPEPIG** [comment]
Get DevTools. Download the zip and extract it. Then move the folder to plugins folder. Start server, do /makeplugin PiggyCustomEnchants and now you have a phar in your DevTools folder.

**Comment by moneymill2400** [comment]
I can't see enchant on my weapon / item

**Comment by MCPEPIG** [comment]
That is an issue that only happens on Tesseract.

**Comment by moneymill2400** [comment]
This happens on genisys too

**Comment by Aericio** [comment]
Tesseract is basically Genisys, they are the same except Tesseract is a mix of both Genisys and pmmp.

**Comment by moneymill2400** [comment]
It's a good plugin but custom enchant don't pop up on items

**Comment by Dragonblitz10** [comment]
Add CustomEnchants book?

**Comment by Driesboy** [comment]
that will be nice

**Comment by Driesboy** [comment]
can you enchant it even with the original /enchant?

**Comment by MCPEPIG** [comment]
Nope.

**Comment by brianzp** [comment]
Didnt felt like making another issue for this as it would waste a ticket so I just wanted to Thank You for your awesome plugin. Thanks a lot @DaPigGuy

**Comment by DaPigGuy** [comment]
Your welcome.

**Comment by QuiverlyRivalry** [comment]
Hi, I am an Owner of a server and YOU ARE INCREDIBLY GOOD at making plugins it's astounding :1st_place_medal:  
I just would like to say maybe in a future update there should be a way to buy Enchants for example /buy berserker 5 and you bought the enchant that would be awesome for my server!
Keep up the good work guys 👍 
And please help make this plugin happen please :) thanks and in sorry if this isn't where u post ideas I'm new to github :P

**Comment by DaPigGuy** [comment]
Might make that a separate plugin.

**Comment by QuiverlyRivalry** [comment]
Omg thx so much!
I would love to make you an op in my server if you want !
I'm really looking forward for this plugin thx so much.
I was thinking if quitting my server because I couldn't figure out away
people can buy/use the enchant, all my friends donated in the server
believing me ,
But what you said now is a glimmer of hope for me thanks!

**Comment by QuiverlyRivalry** [comment]
Hi, 
I just had an idea which would make this plugin a HIT...
If you guys can some how make it so if you do /cebuy add charge 10000
This command basically means you created a command where you buy can buy he custom enchant charge for 10k
Then you can do 
/cebuy charge 
This will buy the enchant charge and apply it to the sword.
If you need anything ask me I. Happy to help thus wonderful project with inspiring people!
I am willing to give you FTP access and Console access to my server :D
Thanks mrpiggy and continue your awesome work!
PS I'm vegan :3

**Comment by PvPsaturN** [comment]
Hi
I really have a big promblem i cant use it it wont work for me

**Comment by DaPigGuy** [comment]
Please stop spamming. Also added support for 3.0.0-ALPHA7

**Comment by DaPigGuy** [comment]
Please submit custom enchant ideas here. (https://docs.google.com/forms/d/e/1FAIpQLScfWdk8OyQ6NNw6KiJxP_4CH4GHnKlaFr4VfZIQojk7OPlyoQ/viewform)

**Comment by DaPigGuy** [comment]
PiggyCustomEnchantsShop has just been released. get it [here](https://github.com/DaPigGuy/PiggyCustomEnchantsShop/tree/master)

**Comment by Aericio** [comment]
In order to prevent our issue tracker from being clogged up by suggestions instead of errors/bugs, please post suggestions only in #2. Current issues will be left open until completed, but future requests should only be located here.

**Comment by amarigamer10** [comment]
Hey luv the plugin u should add custom enchant books u drag on item and make a shop gui for ceshop

**Comment by DaPigGuy** [comment]
1. Already exists, use latest version
2. Will release later

**Comment by MateiGamingYTB** [comment]
You can make an phar?.....

**Comment by DaPigGuy** [comment]
Click (here)[https://poggit.pmmp.io/r/20071/PiggyCustomEnchants_dev-198.phar] for phar.

**Comment by Hexwarriorhex** [comment]
can you please accept my friend request is discord my discord is hexwarriorfir#2006, i am having trouble adding the custom enchant plugin so would you might helping me really quickly?, i'm a starter, sorry

**Comment by xXNiceAssasinl0** [comment]
I can halp

**Comment by TheShinPin** [comment]
You should add an enchant (for any item really) that removes all enchantments on drop, 100% of the time (or 25 percent per level with 4 levels) This would be useful for enchants you only want with certain sets of armor, so you can prevent players from dropping the item and another player picking it up, or another player killing the player with the special item and then using it. Thanks if you actually add this!

**Comment by MateiGamingYTB** [comment]
why u don`t create a command like /ce all and that command to customenchant with all customenchants that item you holding in hand with all enchants disponible for that item?

**Comment by MateiGamingYTB** [comment]
sorry for bad english
