### ISSUE TITLE
hi add cexp 

### ISSUE THREAD

**Issue by antokiller** [DaPigGuy/PiggyCustomEnchants#200]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
what do you mean
