### ISSUE TITLE
Kicked from server from using CE

### ISSUE THREAD

**Issue by omgA4L** [DaPigGuy/PiggyCustomEnchants#201]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

Server kicks me everytime I try to use a kit from KitUI that has a Custom Enchant.
#### **Version:**

- PiggyCustomEnchants: 1.4.5

- PMMP: 3.7.2

#### **Steps to Reproduce the Issue**

1. /kit (from KitUI) and select a kit that has a custom enchant on it

#### **Extra Information**

I've attached a file containing what the console displays when this error occurs.
[error.txt](https://github.com/DaPigGuy/PiggyCustomEnchants/files/3096557/error.txt)

**Comment by Aericio** [comment]
Use KitUI's download from poggit instead of GitHub releases.

**Comment by omgA4L** [comment]
I did that, could you provide the version of KitUI you have? Maybe that'll work.

**Comment by Aericio** [comment]
https://poggit.pmmp.io/ci/Infernus101/KitUI/KitUI

**Comment by Aericio** [comment]
Dev#73 build.
