### ISSUE TITLE
How to Add ce with Code?

### ISSUE THREAD

**Issue by BlackPMFury** [DaPigGuy/PiggyCustomEnchants#202]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Questions:
1. What's Code for Add ce To Item?

**Comment by Aericio** [comment]
https://dapigguy.github.io/PiggyCustomEnchants/
