### ISSUE TITLE
Lumberjack enchant doesn't work

### ISSUE THREAD

**Issue by Diamond946** [DaPigGuy/PiggyCustomEnchants#203]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
You have to sneak to use it.
