### ISSUE TITLE
Explosion enchant crashes server

### ISSUE THREAD

**Issue by TetroYT** [DaPigGuy/PiggyCustomEnchants#205]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

the enchant explosion crashes my server it just keeps on spawning items till it crashes my server can you limit this or completely remove this enchant

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

**Comment by Aericio** [comment]
Can you fill out the rest of the information?

**Comment by Aericio** [comment]
Explosion enchant works perfectly fine. If item drops is an issue for your server, then consider allocating more ram or use https://github.com/JackMD/EnchantmentsDisabler to disable the enchant.
