### ISSUE TITLE
Normal Players cant use enchantments

### ISSUE THREAD

**Issue by Eric-kade** [DaPigGuy/PiggyCustomEnchants#206]
Please make sure your issue complies with these guidelines:
- * [TeaSpoon v1.2.0 for pmmp 3.9.1 ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ Normal users cant use tne enchantments on tools.] Issue must have not been reported previously
- * [ Yes] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ Yes] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ Yes] If possible, provide crashdumps/errors related to the issue.

#### **General**

When i enchant a tool for a other player they cant use this enchantment.

#### **Version:**

- PiggyCustomEnchants: v1.4.6

- PMMP: 3.9.1

#### **Steps to Reproduce the Issue**

1. Give a normal player a pickaxe
2. Do /ce enchant [playername] driller 2
3. Let him break a block
4.The Enchantment doesnt work!

**Comment by Aericio** [comment]
Driller does **not** activate on every block you break.

Running PiggyCustomEnchants v1.4.6 and PMMP v3.9.1 (without TeaSpoon) and it is working perfectly fine. If you broke more than one block (at least 5), try removing TeaSpoon from your plugins list and see if that fixes anything.
