### ISSUE TITLE
Driller Enchant not working!

### ISSUE THREAD

**Issue by BrianZP** [DaPigGuy/PiggyCustomEnchants#21]
## Core:
**PocketMine-MP**
PiggyCustomEnchant: poggit build: [#69](https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants/PiggyCustomEnchants/dev:69)
## Issue Description:
The driller enchant does not work.
## Steps to Reproduce:
1. Download latest PiggyCustomEnchants.phar from poggit.
2. In Game type /ce enchant driller {level}
3. Try to dig somewhere.
## Expected Result:
Upon digging the blocks located in the area according to the level set on the tool being used should blow up a hole with item drops.
## Actual Result:
Upon digging nothing happens. Only the block that is being mined is dropped.

**Comment by DaPigGuy** [comment]
Any errors?...

**Comment by BrianZP** [comment]
There are no errors. Will put debug mode to 3 and see.

**Comment by AffanStarPure** [comment]
@BrianZP 
If driller won't work because you have enabled instant break block

**Comment by BrianZP** [comment]
Thanks @AffanStarPure everything worked now. And thank you too @DaPigGuy for the super awesome plugin!!
