### ISSUE TITLE
Certain Effect Combinations are incompatible, causes no effects to appear.

### ISSUE THREAD

**Issue by KingOwnageXV** [DaPigGuy/PiggyCustomEnchants#212]
I'm using version 1.4.6, and the custom enchantments that I have on that are causing none of them to appear are Distraction, Confusion, IceAspect, and Blindness. I've been using this plugin for awhile this is the first bug I've encountered like this, some of these enchantments are incompatible please fix. 

Also since I'm here certain enchantments could definetly be nerfed, some are very powerful (such as blindness. no cooldown, can barley see infront of you, it instantly reapplies when hit after it wears off) but that's off topic

**Comment by Aericio** [comment]
I'll confirm once I get the time.

> Also since I'm here certain enchantments could definetly be nerfed, some are very powerful (such as blindness. no cooldown, can barley see infront of you, it instantly reapplies when hit after it wears off) but that's off topic

Definitely, these values were never changed since they were put in. There were plans to make these customizable but... @DaPigGuy has dropped this project. And I am only keeping it run-able.

**Comment by KingOwnageXV** [comment]
Thank you for your response and for taking care of this project. I definitely care about the balancing because the owner of a server I'm staffing wants this plugin on but due to the unbalance of certain enchants people are just blind, slow and nauseous swinging everywhere which removes all skillful aspects of pvp such as combos and just slows it down but the concept of this plugin is a great idea which is why I hope to see it improve.

Also I hope you're able to reproduce the bug

**Comment by Aericio** [comment]
Actually, I can't test with anyone (and I don't have a server).

Is it possible for you, or anyone else, to upload a video showing the issue?

**Comment by KingOwnageXV** [comment]
Of course it is, I'll try to record it however it's pretty straight forward. I put all these enchantments on and then when I hit someone none of the effects are applied so all you'd see is me hit someone.

I don't know if it's a combination of 2 of them that bugs the entire sword out or a combination of 3 or all. I just know it currently doesn't work with what I have on.

**Comment by Aericio** [comment]
I just checked on this again, and IceAspect is supposed to not even be enabled (and it isn't even implemented). 
https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/src/DaPigGuy/PiggyCustomEnchants/CustomEnchants/CustomEnchantsIds.php#L18

Furthermore, Distraction and Confusion are also not enchantments in this plugin. Where did you get those from?

**Comment by KingOwnageXV** [comment]
Sorry we renamed some of the custom enchantments. Blindness = Blind, Distraction = Hallucination, IceAspect is just the slowness effect, and whatever custom enchant that is responsible for Blindness + Nausea is Confusion.
