### ISSUE TITLE
New

### ISSUE THREAD

**Issue by antokiller** [DaPigGuy/PiggyCustomEnchants#213]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Hey can you make new enchant your plugins is so nice but he need updates

**Comment by Aericio** [comment]
We aren't adding any new features, it will just be maintained. @dapigguy doesn't want to work on this anymore.
