### ISSUE TITLE
Lumberjack doesnt do anythink

### ISSUE THREAD

**Issue by darkadams** [DaPigGuy/PiggyCustomEnchants#214]
When I put enchant lumberjack on my diamond axe it works but it doesnt do nothing I tried to break log and it only breaks the one log and the connected logs dont break

**Comment by ZZWILLIAMXXTrue** [comment]
You gotta crouch for it to work

**Comment by darkadams** [comment]
Oh and in the future can u change that to standing up thanks you I love ur
plugin

**Comment by ZZWILLIAMXXTrue** [comment]
This isnt my plugin and I cant do code!

**Comment by Aericio** [comment]
It's set to crouching so you won't activate it when you just want to break one block.
