### ISSUE TITLE
Plugin Crash on Server Start

### ISSUE THREAD

**Issue by RealItzBecky** [DaPigGuy/PiggyCustomEnchants#218]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

PiggyCustom enchants has crashed due to the BaseCommand file not being there and it isnt in the github either
#### **Version:**

- PiggyCustomEnchants:  2.0.1

- PMMP: 3.9.4

#### **Steps to Reproduce the Issue**

1. Upload plugin to server.
2. Restart or reload the server.

#### **Extra Information**

Nope

**Comment by Aericio** [comment]
Where did you get the download from?

**Comment by RealItzBecky** [comment]
The github

**Comment by Aericio** [comment]
You should download from Poggit-CI instead of GitHub.
