### ISSUE TITLE
Someone copied your plugin..

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyCustomEnchants#22]
Hi, someone copied your plugin and didnt credit you. Please check Imgaical Mine site

**Comment by BrianZP** [comment]
Yea I was about to report it too!

**Comment by QuiverlyRivalry** [comment]
Yeah that script kiddie ;/
is there a way where piggy can claim the plugin, off the imagical mine site?

**Comment by QuiverlyRivalry** [comment]
Its also disgustng that fact that he states he is a Plugin Developer

**Comment by BrianZP** [comment]
DMCA claim! But only @DaPigGuy can do that! Also I even unphar-ed the plugin to check it's owner. And clearly it was @DaPigGuy .

**Comment by QuiverlyRivalry** [comment]
Screw him ;/
It already has 51 downloads how disgusting 
Remins me of LEET stealing layers plugins

**Comment by QuiverlyRivalry** [comment]
Hey brian, do you code?

**Comment by DaPigGuy** [comment]
Well they can go kill themselves...
