### ISSUE TITLE
uhh what

### ISSUE THREAD

**Issue by jennocool** [DaPigGuy/PiggyCustomEnchants#224]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

I can´t see the name of the ecnhantment the enchantment is there and works but I can´t see the name

**Comment by DaPigGuy** [comment]
No information no help

**Comment by jennocool** [comment]
wow I gave info xd

**Comment by DenielWorld** [comment]
@jennocool I suggest you pay better attention in your English classes. In other words, learn how to read guidelines.
