### ISSUE TITLE
Upgrade books by combining

### ISSUE THREAD

**Issue by BlobKing21** [DaPigGuy/PiggyCustomEnchants#227]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**
Books with the same ce and level won't combine

#### **Version:**
- PiggyCustomEnchants: 2.0.3

- PMMP: API 3.11.1

#### **Steps to Reproduce the Issue**

1. Enchant two books with the same enchant and level
2. Try combining them, and it doesn't work

#### **Extra Information**

Unless I've just bugged something out, or am doing this wrong, the books won't combine. If I'm just being an idiot and doing it incorrectly, or if this isn't a thing yet, I feel as though it should be, but please let me know! Thanks!

**Comment by Aericio** [comment]
It's not supposed to combine. We'll see about adding it.

**Comment by BlobKing21** [comment]
Sorry for bothering on Christmas eve, but I just wanted to know, so thank you!

**Comment by BlobKing21** [comment]
Also, maybe it costs xp when you combine them? Just a thought :)
