### ISSUE TITLE
It wont work

### ISSUE THREAD

**Issue by PvPsaturN** [DaPigGuy/PiggyCustomEnchants#23]
Its said PiggyCustomEnchants\CustomEnchants\CustomEnchants::setLevel($level) should be compatible with pocketmine\item\enchantment\Enchantment::setLevel(int $level) in phar:///storage/emulated/legacy/Genisys/plugins/CustomEnchants.phar/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants.php on line 226 pls help me

**Comment by QuiverlyRivalry** [comment]
I dont think it works for Genisys using this build...
And btw dont suppourt the plugin on Immagical Mine forums, its a fraud and a copy of piggies send hate to it

**Comment by PvPsaturN** [comment]
SORRY BUT WHAT DO I HAVE TO USE SINCIE GENISYS NOT WORKING

**Comment by QuiverlyRivalry** [comment]
Pocketmine, I use it.
My server:
CastleRaid.us.to
26211

**Comment by PvPsaturN** [comment]
CAN I JOIN UR SERVER?

**Comment by QuiverlyRivalry** [comment]
Look at issue #13 it will answer your question.

**Comment by QuiverlyRivalry** [comment]
Yes you can.
https://minecraftpocket-servers.com/server/67914/

**Comment by PvPsaturN** [comment]
Can u tell me where to download pocketmine?

**Comment by QuiverlyRivalry** [comment]
Okay...
https://github.com/pmmp/PocketMine-MP

**Comment by PvPsaturN** [comment]
But idk what do download do u have twitter?

**Comment by QuiverlyRivalry** [comment]
You download the zip file, and run the .cmd file

**Comment by PvPsaturN** [comment]
Where is the .cmd

**Comment by QuiverlyRivalry** [comment]
There is a start.cmd file.

**Comment by PvPsaturN** [comment]
I found that then

**Comment by QuiverlyRivalry** [comment]
Okay cool

**Comment by PvPsaturN** [comment]
These what i see @echo off
TITLE PocketMine-MP server software for Minecraft: Pocket Edition
cd /d %~dp0

if exist bin\php\php.exe (
	set PHPRC=""
	set PHP_BINARY=bin\php\php.exe
) else (
	set PHP_BINARY=php
)

if exist PocketMine-MP.phar (
	set POCKETMINE_FILE=PocketMine-MP.phar
) else (
	if exist src\pocketmine\PocketMine.php (
		set POCKETMINE_FILE=src\pocketmine\PocketMine.php
	) else (
		echo "Couldn't find a valid PocketMine-MP installation"
		pause
		exit 1
	)
)

if exist bin\mintty.exe (
	start "" bin\mintty.exe -o Columns=88 -o Rows=32 -o AllowBlinking=0 -o FontQuality=3 -o Font="Consolas" -o FontHeight=10 -o CursorType=0 -o CursorBlinks=1 -h error -t "PocketMine-MP" -i bin/pocketmine.ico -w max %PHP_BINARY% %POCKETMINE_FILE% --enable-ansi %*
) else (
	%PHP_BINARY% -c bin\php %POCKETMINE_FILE% %*
)

**Comment by PvPsaturN** [comment]
Iam new at these

**Comment by QuiverlyRivalry** [comment]
Im sorry I am new too ;P
You need the master of minds, and pigs the one and only!
@DaPigGuy or @Aericio to answer your question.

**Comment by PvPsaturN** [comment]
Do i dm them on twitter?

**Comment by QuiverlyRivalry** [comment]
I dont have twitter.

**Comment by QuiverlyRivalry** [comment]
Idk their twitter.

**Comment by PvPsaturN** [comment]
Ik but Pigy has a twitter?

On Jul 21, 2017 10:31 AM, "QuiverlyRivalry" <notifications@github.com>
wrote:

I dont have twitter.

—
You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub
<https://github.com/DaPigGuy/PiggyCustomEnchants/issues/23#issuecomment-317105306>,
or mute the thread

**Comment by PvPsaturN** [comment]
Can u just tell me the pocketmine apk because i have the phar

**Comment by DaPigGuy** [comment]
...
