### ISSUE TITLE
InvMenu

### ISSUE THREAD

**Issue by ASANITA** [DaPigGuy/PiggyCustomEnchants#234]
I recently made a plugin with the api of InvMenu that opens a double chest. But when piggy custom enchant is activated on the server the plugin gets enabled (speaking of the plugin that I made) but when trying to execute it doesn't work.

**Comment by provsalt** [comment]
> I recently made a plugin with the api of InvMenu that opens a double chest. But when piggy custom enchant is activated on the server the plugin gets enabled (speaking of the plugin that I made) but when trying to execute it doesn't work.

The template is meant to be followed.As well please describe more then doesnt work.

**Comment by ASANITA** [comment]
> > I recently made a plugin with the api of InvMenu that opens a double chest. But when piggy custom enchant is activated on the server the plugin gets enabled (speaking of the plugin that I made) but when trying to execute it doesn't work.
> 
> The template is meant to be followed.As well please describe more then doesnt work.


OK, actually when I try to execute the command that makes the plugin open the chest UI it just don't do it. As simple as that no errors on console
