### ISSUE TITLE
Forcefield BUG

### ISSUE THREAD

**Issue by RubyTemple** [DaPigGuy/PiggyCustomEnchants#235]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

to some players the forcefield deactivates itself, they still have the spell on the armor but it does not work, if the same armor is passed for example to me it returns to work but only for me
#### **Version:**

- PiggyCustomEnchants: PiggyCustomEnchants version 2.0.3

- PMMP: 3.11.2

#### **Steps to Reproduce the Issue**

1. idk

**Comment by BlobKing21** [comment]
Update to the newest version of PiggyCE, they just released 2.0.4 yesterday. See if that works and if it doesn't work then pop back here and let the devs know!

PS. Aericio, I'm just trying to help, don't delete my comments xD

**Comment by BlobKing21** [comment]
Update to latest PiggyCE v2.0.4, see if that fixes.
