### ISSUE TITLE
PCE: Error json

### ISSUE THREAD

**Issue by NoiiHiri** [DaPigGuy/PiggyCustomEnchants#241]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants: 2.0.4

- PMMP: 3.11.3

#### **Steps to Reproduce the Issue**

1. Reinstall Plugin

#### **Extra Information**

https://crash.pmmp.io/view/3555978

**Comment by Aericio** [comment]
> Operating system: android

Android systems are not supported.

**Comment by Aericio** [comment]
#225
