### ISSUE TITLE
Error with mysterycrates plugin

### ISSUE THREAD

**Issue by mikeygio10** [DaPigGuy/PiggyCustomEnchants#245]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**

Error msg when you try to put an enchant on and item in crates
#### **Version:**

- PiggyCustomEnchants: 2.0.0

- PMMP: 3.11.4

- OS: Linux, linux

#### **Steps to Reproduce the Issue**

1. Putting enchant on an item in the crates plugin 

#### **Extra Information**
PocketMine-MP Crash Dump Wed Jan 22 00:45:59 UTC 2020

Error: Argument 2 passed to pocketmine\item\enchantment\EnchantmentInstance::__construct() must be of the type int, null given, called in phar:///home/container/plugins/MysteryCrate_dev-108.phar/src/JackMD/MysteryCrate/UpdaterEvent.php on line 173
File: src/pocketmine/item/enchantment/EnchantmentInstance
Line: 41
Type: TypeError

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: MysteryCrate v9.1.1

Code:
[32] 	/** @var int */
[33] 	private $level;
[34] 
[35] 	/**
[36] 	 * EnchantmentInstance constructor.
[37] 	 *
[38] 	 * @param Enchantment $enchantment Enchantment type
[39] 	 * @param int         $level Level of enchantment
[40] 	 */
[41] 	public function __construct(Enchantment $enchantment, int $level = 1){
[42] 		$this->enchantment = $enchantment;
[43] 		$this->level = $level;
[44] 	}
[45] 
[46] 	/**
[47] 	 * Returns the type of this enchantment.
[48] 	 * @return Enchantment
[49] 	 */
[50] 	public function getType() : Enchantment{
[51] 		return $this->enchantment;

Backtrace:
#0 plugins/MysteryCrate_dev-108.phar/src/JackMD/MysteryCrate/UpdaterEvent(173): pocketmine\item\enchantment\EnchantmentInstance->__construct(object DaPigGuy\PiggyCustomEnchants\enchants\tools\pickaxe\JackpotEnchant, NULL )
#1 plugins/MysteryCrate_dev-108.phar/src/JackMD/MysteryCrate/UpdaterEvent(209): JackMD\MysteryCrate\UpdaterEvent->getReward()
#2 src/pocketmine/scheduler/TaskHandler(169): JackMD\MysteryCrate\UpdaterEvent->onRun(integer 428)
#3 src/pocketmine/scheduler/TaskScheduler(206): pocketmine\scheduler\TaskHandler->run(integer 428)
#4 src/pocketmine/plugin/PluginManager(703): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 428)
#5 src/pocketmine/Server(2670): pocketmine\plugin\PluginManager->tickSchedulers(integer 428)
#6 src/pocketmine/Server(2403): pocketmine\Server->tick()
#7 src/pocketmine/Server(2250): pocketmine\Server->tickProcessor()
#8 src/pocketmine/Server(1811): pocketmine\Server->start()
#9 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#10 src/pocketmine/PocketMine(297): pocketmine\server()
#11 (1): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.11.4 [Protocol 389]
Git commit: 13f28d8454fc499e1869190ccbbad077bff5853f
uname -a: Linux a8492fdc-8684-4d2f-a0e5-3078a450b7da 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64
PHP Version: 7.3.13
Zend version: 3.3.13
OS : Linux, linux

Loaded plugins:
MobStacker 2.0.0 by TheWalker0 for API(s) 3.0.0, 4.0.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
ScoreHud 5.1.1 by JackMD for API(s) 3.0.0
PiggyCustomEnchants 2.0.4 by DaPigGuy for API(s) 3.11.2
MOTDShuffle 1.1.6 by TheDeibo for API(s) 3.0.2
SignEdit 1.4.6 by OtorisanVardo (alMus) for API(s) 3.0.0
AntiDupe 1.0.0 by  for API(s) 3.0.0, 4.0.0
Slapper 1.5.2 by jojoe77777 for API(s) 3.9.0
CommandDisabler 1.0.0 by ARTulloss for API(s) 3.0.0
TeaSpoon 1.2.0 by CortexPE for API(s) 3.9.0
BetterVoting 1.6 by Twisted for API(s) 3.0.0
CommandCreator 1.0.0 by SchdowNVIDIA for API(s) 3.8.0
AutoInv 0.0.10 by JackNoordhuis for API(s) 3.0.0
NameSpaceRemover 1.0.0 by JackMD for API(s) 3.0.0
AutoRestarter 1.0.0 by  for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
StaffUI 1 by Ameer4Real for API(s) 3.0.0
CombatLogger 0.0.6 by Jack Noordhuis for API(s) 3.0.0
PMEssentials 1.0.0-dev by pmessentials for API(s) 3.6.0
DevTools 1.13.5 by PocketMine Team for API(s) 3.4.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
ChatCensor 2.3 by EvolSoft for API(s) 3.0.0
iProtector 3.1.1 by LDX for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
SeeDevice 0.0.7 by Palente for API(s) 3.0.0, 3.0.2, 4.0.0
AdvancedJoin 1.1.1 by tim03we for API(s) 3.0.0
PortalsPE 2.0.0 by luca28pet for API(s) 3.0.0
SkyBlock 3.0.0 by GiantQuartz for API(s) 3.0.0
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
AntiVoid 1.1.0 by FiberglassCivic for API(s) 3.0.0
AutoClearLagg 3.0.0 by Twisted for API(s) 3.0.0
RenameItems 1.1 by Wertzui123 for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
Alias 1.2.3 by ZacHack for API(s) 3.0.0
StaffChat 1.1.2 by Thunder33345 for API(s) 3.0.0
AlwaysSpawn 2.2.4 by Philip Shilling for API(s) 3.0.0
InfoUI 0.1 by Ameer4Real for API(s) 3.0.0
OrbitCore 1.0.0 by ItzLightyHD for API(s) 3.0.0
OreGen 1.1.4 by Xenophilicy for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
MapImageEngine 1.1.3 by FaigerSYS for API(s) 3.0.0
AutoXP 1.1.0 by JackMD for API(s) 3.0.0
MysteryCrate 9.1.1 by JackMD, DaPigGuy for API(s) 3.9.0
WarpsPro 1.3.0 by nikoskon for API(s) 3.0.0
DEVirion 1.2.7 by poggit, SOFe for API(s) 3.0.0
EasyKits 1.1.3 by AndreasHGK for API(s) 3.9.0
SellAll 1.3.0 by AndreasHGK for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
PiggyCustomEnchantsShop 1.3.1 by DaPigGuy for API(s) 3.2.0
AllAPILoader 1.0.0 by TheNewHEROBRINE, JackMD, OhhhAlex for API(s) 3.0.0
Texter 3.4.2 by yuko_fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421, No4NaMe for API(s) 3.10.0
PureChatExtras 1.0.0 by ProxyTechDevs for API(s) 3.0.0
SkyBlockUI 1.0.8 by ItzLightyHD for API(s) 3.0.0
RulesUI 1 by Ameer4Real for API(s) 3.0.0
VanishV2 1.5 by superbobby for API(s) 3.0.0
XPBottle 1 by  for API(s) 3.11.4

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPGtz2za2fwWjdO4mHVFv+aGOO+vaTuNdO9ZazuPuspOBSEhiTRIsQVpWOv3v95wDkARpO3Yc
9d77odmHRRA4OC+cFwH83lrINOLZpxuRqkDGrcmg3cqCSLQm/fHu/s54uD/eb7dCrrKTNJVpa/J7
K9sk8Lp1BX90W7sVCaX4ElsP02UeiThjA5ZwpYTPMskS6V2LLApi4bpBJiLXFbG34nGGPV33pHo4
jVXGY09MJp8+eRIe0tzLXr5iUa4yNhdMLli2EgxRYEGctVmchyFbBjcibjOPhyFMGMQsWfF00u12
VzISXYCTcZg77SZhvgxi1T3fqEykm6OUZ+KTL26cfm+vg2O6KvW6/+De9flxrVP3XeLDn/QE5smg
Z8JkzEKAyfq7Q6B/AVi8DkJkwANTT4kF5/DbOZ9Wc1Wc6SJjuhZfuvewBafG6fRUzwAAgxHt1mTU
BzmnHFom/2m96LHtsOYlsOPV5Bnydn605S3nvwovY8d8Gix/zjeuC3+XmyPQARmZwaqECb8yKUP4
kwTeNb+FORHNRGama5u9fXd2xl4B7S/62yJ00NsHQnU317X7ua7d0flxKbJLseap/5IwGLCG2JS3
En4ego5ccXX9hsc+/H7Z33kqfBlf5vFLWAxiKVI2GuzRNMMvTzMrnoCQnYbEyp6ua2Hk/JjeM82o
OY1mb3dKf855DFYhfbnbG355jhId58cI1svVKhXcfyN4ms0Fz+7MOm7OOhPpDdKys9trTKTxAQ2y
EXJ+zEBVyknVnQl2HppgdIcS/UZD1BLefWjwYNz7wuBpKj0wozLVUPYegNLf6/cfgAJLKc306P3m
6Mr+vBzsjh4AcM8a/IkrcQTmX51J7ou0zUy7PTzPAlx+5yC5M7lcYi8AEsTL//R3fmFNS1i+HIzu
vixWp16svS9Rsb/b1CnNID20z14im1LxWx6k4qWZcrf/C3u2ga56oBl+1frlj3ZL/OUUH3aK2/BS
wGON4KcgvpHhjcB+ADWIfZCrl7WK99BmIwftnvQFimY4gHdu1v3+e/b3G54ii9j3XegwHNKLJA1u
YAT7LhQ3IvwBX4zgBf4dFyPxYYce2PfsHoxZKReZdrDzrumMv/eKgX9PeMojezz7zmJF7QUpFAze
bwxG7It/GmN2Rv8PWmDBgqGjnhmKtI76mtZ8HgYeW+Sxl0G4x2yFegitNs1p5jpg/Ve/IzzNVDf7
LlsFyvnRJuOgNhwZOhrWexewKpaPRtTjD/w51twf7VjcHxUMZZciy9NYVSpP6h8om3oUwahie0pD
bPbi+32LPePevewB340rGtbaxB6NDBj3DUkG+F0+/ND6468Y668Y668Y668Y668Y67kxVru1FDCU
h+jJY46FiVYNDGAyB/5VBYzWsNPvd0bYngeh35r0d/f22q1AoQVqTRY8VAKChlRm0pMAdri3D5ME
GFT0h4vBnr83Go8W3mh/X/T3dvb7+z3Pm8+539vdnS8W473xcAGwU34dBnMY0+v0B50etOQGu7Mg
zm8Z3xvtDxa+5+zt7I2ckT9YOLwnxs6wt7vHR+PefNfnbNTpjzs9Z3fgEJHgeV7s9Z138zzOcjY7
n7KrXLC38oYNdlh/MBn0Jr0Be3d1xAa9/j673dv5tIN0YlFg0trtAOEYd30WsU9sMM/w+pNUBWbQ
QA8hPZThlUL+nsv5LANzKFKL21Zju1VxGYgmsnmerWSq0MVdrcQHHkLHHsqNJwE2Dk2/Ef2FdhHz
OUSkrQmsARCELxLAF8fDOyUX2bHdgJaqhoPr6kWCISL8QG24mF19uLg8O4amtZgrcIYYPwBlp/HN
TAiLFNNgk9G/S8ZPIejXG5kGn2Gh3qHkmRTUgLquxuRriJl5MhVvct8ip2yyCRp3+p1+nSDt4bZF
SeEvi9mrX08h454ow17Z97xtKt2oTlwRwNTIAwMweC59j0RE96P4RbpXWZYoMIdgZFb5vOPJqFtM
0r0HXBf5dH5xdTxb5YtFaCuw3VrX4n5n585iPBbBXDbE/my2WFNrN1RRPbs6vLx6N72rssEyPvHR
slYqWzTVsR81sb+APCpQPH4PMZ1kL3l4nqtX29LgAokmHU+WXg27bgGO5HYYZ8FxnthCK5u+bHca
xLXZN1nMYlLXtab/WjrJaL0V2Vqm16pbAkLRhjxJam6iaKkTOQaFqwn2V/mrFLv4rybN/edTqvTE
zxZmhVG3oAEIPJJRBEH5MYgZMLIJbb55xJvA0sjDUKqteZISoOs2UHkaCyzSIZQ1uAHFV4LPEolk
lKSWTXUaB00aj2SaidvpybZEWsB7iqEpJFqM6dxuPiM5P4kM8rf3MoOY1CKp1lwnq2lA1wEkhP62
xGbAua6NQf3pKf7TiPwIkrdM3qOWxYtHtBLyMl+u374/PT49rFG49w1m1YJZ6qbBp/n8jHVqg+82
oKHhzTMJUZVtd02LzQpgRKffuxsevZUy9Vd5sLVV+isAjQugrgvTySC+AWtcIvWoqN8CGbOEe+JS
RPKmZoPuvHpE3H9OBNjE4mn2pxDWpaBcukZXvf2r/OVziYlwWWoBpcXMWkw2Io9S9EGmoT+FpBJr
0hVBteZ6JAtrrS4kHgZ5uNmWkDQ0110jBonG4GvsqbXyziG9XwQi9K1M3SmqCFkqRDfiWDvr1qjF
KCHji8W7UztKMC010TYcZiREOroUkPJvy2OWECFXKRF4iqmd80xXW+qGtmpu2padu+uO/dm2xSOE
QkKI7KyN3uMJ2fmJUgJCOx7WMjG7+c5CdLCUUqM0wa9dRX+bzp2vpZOMAFCRhCITh9PTVkW4PQlk
YhaKTzc9x+LmCkvZFq1lUyOlGnbGdSKrwhOD0Ciq0Tl6vjyL+V3XwuTrlmiFWbeEgcLNUzEVaVST
bNnWzMGGdWp3Rq9f93rsvxisaKxHnsaLIA6yrVmoT3oCEGSBkfXzGQECjTVWqYKDC3nFsyMRq3q8
VDU27HKdCyc3MpwBBduiupoX1qqNwxMEvl6vOwLwQdid7BppC4y5rdFmNdq0De+Whs6OP26LMADl
utXMz87HAI5zfjQ96VpUAKEnnoxltEGDUBFqNdZrYLvNvFPGYg7/2xaxBpzrCo0BwHTdGjaPF/SE
gKUaeHapoGprOpbdhiXiIVg+cU+dVRd5vrHeWuKB3y0qlL56RRosMeLzb/AbpP8PGdgZZq25WdFq
6GoWRL3hemsiNOAg9DM4/CrxI1YDo8f9J+Sd4IAg+bU/UBRtj1TMw9zjg71EbM26lADBlBZIPN03
zq43VPKxNbJoqhuSO5T8HPA4+1cO8fLnbdGSShn1d0EDDQrVr8doydYBZtWkgzZiWFfNwyygONUu
q1aNj5Svjj4LbzU9hxWBHup9cBtcH/2bNoBu8kzl1wH8vobQO7jeWrTn4ZRJBBEX+McIMaWQHqRq
Y/21S9MipGsBMhXM9zLwGxVMamqu0IYSvA7mIl3il8yjAEzG1r6dYJa/uuLXQbwMNz8FMU83uq6J
SFW/nlPhvAd0t4RnMtWjUPD0jC+XjUy1an9kcWy5lJQVpSRMWj1EIgQkdNJq4/S1zDBoHqpNmEfn
R906PGDGpUDqTzNRCyjt1oaC1NnwQcAizIP+YLgtTlQQXddC49mxRwWva1OF5UT8lizSZupQa75T
JXXmIuNPsiB/hq2Ya9zMxp0Gpt9iL2qggDevZRrV47Kipc6RYXNdPPAxYPANqXEJ0XUNEuWPJxWm
woDb8tXPTcE2UoR/c+8NpORbK1fgnFqFaVfIkzw3ljUwnWjWWqitabYHzU+FeQzyHA6Ho/HWyt0W
TFN1QVSsn88xUBrosRSqSPQqcCS9Nd+oWcLXtRjTaq3HY4Pmx+TpKgiDhM3gT4gF+S0xIyGwykAF
u00YKcTo7haAh76mQvota7U001DPFP5Xi2klBo/q50U6D7IjmdrJTtX2SPX6NPt8FixX2ebN1krY
FkjXLRF5eqR8kYqfRVwjhhqaK62hXx9FLEkZvK1VUSyQSAliUfx9UvqSp6JhN8qmZn2o37+vQPRV
hFjVp7uFv9ecdt0qyPthoo+Qdcoc8henaG89UDvShsVC+1srR4U9OefJacSX4iRe0nb0KmGov2hK
veEfXvNgKdLZf8+2JfMSICqsjUnz+anfYj5OG6Htx+ljsf6f80lJz/3s+M1sKTYUoATtIwGW/Oon
BSpC9x/cPdW+f6fR/rfTXN94/G2U1wjDz1I8TWg9WZ+kiqZHgrM4uJbqGt5uScQFPNctMKh+Palw
f/I+SIPa/oSyqRmgNapliVwuac/R7OL11upHGqjr3hAKrgtBt/llofWITz/havPPoLYFrmx6xKgc
xj7krurNz//8Nn2s11CpFGBaWvfv1rP3GBUouG6BdvXrKUoMOrxaXnci0dUV0TA8DMNaPVS3PKKq
D/DiUWdkkf7FrVQVmQah8seTviMS/2YrmdTCt1qzTSBWbhsfnmY8zDbT4FaEkIB9/jOIrM/gujZ2
NwOgF349UaIKQSUIqrPkD+z5JHBf3PdpJqzLvf+EvZ+DR0OQ+5X64WXxxL2hiPGDL7a8RxRB6v2G
oIbTU5ND2DmP1fxIeH21Em/F+s3J5cVPl6dvT9rmREybXaxWq8NQ3H6bxbQ/r76WWDjQoZZBrmJu
MR1EARb2T91seiVu63tJTEO9NDdq5r6b/Fp+squ30SJaxOIaeVR8M4Jfy2DNU44eZCVlpjL+6eTy
XW88RIW8kksek7Wfrbgv14cpuppznqYy7o0G2OWtHL3l53XX0/96ThaFDKsUKK834EeTKALV0xTj
FoD0OV9rSi50Deus9ODkNku5uidJMC8eUTFw8bebK+GtqOz11QkDxeNfMF418FUmoHFrPn/Nh5D6
3pWqsUnu3nYS1lpKXH7seGoaW+H39Dz2Mg+FqlFZtPyf7dCpEHgU+/c8DtTq/cBCv2xqfMipU6Dy
RKRzOZ9vLQ2vILpugUP16ynEfJz+JLOstt2/bHpYGI1TD6Nnb+/Pf1MYzVpTPoIxHh3CE8kCTAUx
tXPP+S4Y4zixdNbBZ5769OTr3coOj1VAuk1HyjpJKoGDWSDwcNKLafnEjmS8CJYMT5O7qRu/+CB8
8FAxGwxYrzcZjCf9sTkTNehhBw3PCZID/G4O/8FGzRLntxySowNki9UzkWl20N/vDwfYSF069bZI
Zv5BjTimj/Phy/UKOOKEgYIB+MzjWOZ43DYJ+QbAc28VCH1uXR1AeoATY+XPMZvyQKoHhGPEb80Y
daBJWQJ3I+kL/X4hU4BatsnFAluByT6evymek5vEzOIHi0XgQUC/OSAq9EG6TKaOEhnuN1YH2ExH
sB3UuANdkSzblBC+1QUPWx8cn7w+fHd2ZfE0hUCpmBx/d/CKg7VM/YPv6R9wBNJxR/EbYRC7CcQa
1YBOJR+MsOl2Lm8d1GrTJeTxMudLcSDiJT7jMbZy72FnE4WoJAytHJ68B/3IgTI8sY1qwoBTrCYu
UBsGYY4SrCCd8VTQEXJw8HiWnGfMQ8nRhQpB7IW5r29NuKOeCGsmo+LahSZMxReizSS8SRWCZHNI
Hq7ZRuapgcWCBQMJBouAZgDh4UUG4QYBQyBWguv6YsFBfIqtZfy3jOHZBJ4y5GYExOLFDhvEkA6/
E93rlYhZnixT7gOAjhujjmtgEzdm7MWHlUDE8PoJBSaAAQhzUhR4kMKKDHmmb6cwqII/4QAY+BmK
jPjl02YQtqITy9gSIWStm4XUJoxOWeILtcoziIlix9yGMWFuS68d5oVSCd9tEWYQ8sk1w1UEyBQH
yNlNwNm/cEFiH1qZxb7TCaNVjEMhJFszTjcwSEDJTKSZwQ0olisQM1hCYDWRCGEU9AQr6isEUr1x
btCOK2FNcEKKXkACwhkuOAYqAVxHdOcbZmSF/c26KF9b3HjxIQCOyxgEx32fpUJp+SKqeD4ZUOIK
ohW6RgGkOhfIFeC++C3nIcqFbvVgNzzMBXtpJgXT9wqh6xlhRQo0Xw7IFTeBTuA1zf02j+bAdlDb
Q7WJPTwTzvBkDyhqhzq8w5tJcO0UlGK3FUSxMgf1gO6qzWjvATOmBBZcG3gRAe8UeifiDfgIbIvy
GFQUu2jgM9IfoAnUGMK1AFRYABuAJFoacYkc8tYgdLrAxYB9UOnbLMj+BuzLUhrmC7SepJONwewl
0AACZwNiC5HhGEonBKq5GDhpX5rHMYrTR3MnExICfURVHQaRpfnNIoy4mAeh5Kptr26jmciRNM2T
TLdqhiFjIsDN0EXCBYUDNsEy1CuO38jAB7TvxwB1BHVOAqNBuzqWouHFCrpTqWngTMBJpBu96n8O
5Ry0B10/0+2w0KIgQ+MRiSWfbzLgOJtpVveIudpJ0/ArlNo6IM6TRoFVWDsaUKFkiihcBIAimDxx
QzeYSLZIhSim1EoO0sppeS4lCApPDZBW4ERLQtMh1Cash1TA7GTjM7qs4P89BRhLfQl/9NXfhr/K
ZEIoGPtcomTAKQbmQ98xVCKEsxZY9XuDkUGMjMAHWhUGP/W3LWBI60JfzoIGxsvBu8Xg3Zi4FV5O
1l1qlPWKRG9Y9ha3HsQcqqJIG66Lq5MJu3pzOmNnp+enV2C8p2enJzM2PblkEJr+8+SyzaATu7qA
Xifsw5uLsxM2vbw4OpnNOk0TUOPHYLxj2DEVaSDJ46MhVkigtxJkkokbpbHtA+/B1/hkW6iLg9V2
bWYJFESsQCcYaNAmpPchZdNKBvEjetgYu5nJCLIGAqa3MuTaI9EcF+hDMJCgAZ27vRndiEOJAIgt
ER7GG5qziK6Wqx5b0gDqJRJVkTrsGVrVq/tRMpQPDeVLns5hZTieDEMd2ZIBup+7tNQQHTOKmVFg
uyMe5xTd2JhA5JeDDr5qFz6hqYSFGmr3ulgALE1vVC3BDrvQNl8rPIQnMg/9EpcAnMg6ZhX+SgNO
CH0gdKfXM7TCbK/JWNxxkqQ6GkJJ2yKVUeFs9WjTw7FV05YwUmMkeUc32D0qVdOOWRGRoshSSdsO
CkX28yjR4ZuOEZl54eCLQl7H2MkMINwJzYICeAI3D4ud38NgcNrg+GCGG1AypXKBhiFbgdSWRTiL
Rgtnq7BqF4LUMYKJWjsaG+z6IJ8wa/JWeXytCtyPeIKtQZRH4GNxwwgrkg0UJNM5lsai4iuuF8NK
WjF3dQyi+cRgRBM6GGbn4HRHpcSOpX7V1GmMjdDqafi6c7GENCzT0aaMIgfHg/xRlLThUV+KVSB8
RO4BdjrA0FASvCMDMxkcoymsqINhhp8mAzczY+cq2kUG4p6/Au6XQX1JD9041kfHJ8ZFQGi2kqEO
Mec8g7wYQ31CWeElY8w4GbJtOrUyb7VrmYsy2NTu7YUtpeIVmtV0kyHwNnP6lgBJeDSxkxXIGBdA
VruKY/X9ZDnGw0Q5JksU6ONgaDRoddgbiAVBlw4ouGNH03dtGAs4zGF9rQMf1J5iBW09S/gOwZ+w
3SLsriJyRdyx+nbYoQ+GasXDRRdyVZ0m+AJ02EwFkzIs1aCCWQuxcnsWMDsVOblFq4YhJg/b2mji
1B+CGPI1IA2sjyBbhpH0u2k8LeLwKvnENAMH4c1bCDNP4sQxz43E59wsSBV8FqWoMWIvJIwnuYpo
CiJ6rTmW1x3tD/SgVx02NWNCni5pADdZsFETmnGR8iVSB+ICslQSUjCDqW2EVyKCHeApivAoDLA0
Q7k6XmUkVMbOr94RpgpIQrLnecawNkBSrqbTeUenMENRljs4akLY4gLwxTxfTopc5kfWxxzGRHKY
tdL7ImNVOpkXRSaLw4yi9BGYtlsa2tFKQo6KylmkMKJIUsm4+TzjTPGbwohi9aUoSOG7ar1z8Olg
CQTPChsDmOpLkoqQmdItUCEKV1QCERqFL7H0cLMcjQU+nvMN8BCVBQ8DmwwWzb+xmWS3nOKdnlJV
1qIoOdnliiuqN2gF0PdU60oN9TXSzpVJ9T3cyq3tghnj6DETlkBAcROEOI22eWY9m1nQaPN4WQbV
MQ4Lm76jXfSqla/uLRHpLO8wkjnq9EIbZ6PiyEpd5CNnhMuZcncQDP4mbwKDL8m3WIOJ8FjoXHEu
NLC5WKBGUt2O3MGq0AASOpUZa15Kk48TleTDymS8iWqiL0qD2QQ4gPuw7N2PJk8Bkk91F1JEQLYY
jH9LbIak3ZhJOzldtacsa0F72mkiqqtapZjTY5psjt85FC1J5KdIUdIQ14LpipihjpnKQ+HtaEyN
dIDnsAF7wZaQs6iKPVV1o+RQ5y6LzGJd84CSGjAcEPFr2SQyycNCGc0Dmn3qY0zEHs5HwbCTmFWN
xhUX6oQVYSZVTnU5Z2IcHlafKMXSzdpfGHHh5tKyLuBXbEN1d/A61EZTudrqzckKIrOFtAQCi8zR
XwzLniuJgiFUOvj5sRNIwjiW8SbCFAHWR4blPE9VqGPeY96z6j2RQBaLL5cpJJu6sFRW7jCQwns0
r5v0EX6wgC+OL/AaOsfYQO0K0CashY5DOaycNc2oCPGKAGrrWLVl8Dwl57VmauHcYSrIU783ugRO
L3aM6bbDKWqXNusgQo1RTawqTxvMY7LibYYnBshfZWXEApZ3ISCLBhGCAYrRH+i3hV/RNSNeqxqZ
70WWv8khOgPXRkassBUGIElevy/muCNpTast6gxS6NJUG4eEQLF/ETegZNFe4oRUDjODitJnp5rA
vLFnKLj5ZZdnrLaWrl4VVpWhKAtnQWb4WdQTVqaRDAYmBCbGNAYDy7MQxvsUZAWLEhBE6kCILvaj
ASqSbG3iAJ6xkIVj47id30TwEHRxPNhunjAGAByNrCaF0PQ70Fus9kzYf8h5g/tsU/nnFwRKwXnl
Je2PEEQGBlJp4JsEu/jwQ5nzfQ6L/Dk5aEWxJCVmuBUMcDXe1kZfz0s46J8MPxWhU9DOq5pxwl6f
HV5NBj/stsf7t/328HbYHvzQ/8EXntQm9iVeIOGhbT3Y62lLrJ9G41c66tH1fjuv1SscXQvw2JSd
KPKguhFIzdswfcVmnhY2uQjm07KQTxYH4ICn8uhLjCoY5hRfGUAXdHj34jWZGpqK+teA0KkE0/LJ
anEo1upUFTKZUCoobsHwKZMHedcYLiuK+YEj8wAC1Y1Omakf0hvgFb6h9iJ6zWgqCT7EImlpq1vt
Fm7eiBVtmJ783tKb7qvbIX3aCVs9h8H8lj6nlS2gFLFStabEqwNRvwGSYli7dVJfh1k+zz0IvVZ2
C35Jin2e1trSTZJJOrmgd3d55iL1qkee1lABD49nN3q9Yb8/2IeGX5X5xr9Lu04WQUj7gKoRi6x2
PebSrz1FtZcrcGc1QiHI8/HLtdU2m57VGIjLw9dXgQ6Ihmiuv6nZvaIN8Izu5TS/2BivIhpg9Z45
eKHnuDfq7cLP705hJe16Hvx3f0fs7I4XO/7uQIy9RW8x2NldjPZEf2fXG/D5fDBk35F04qzGo+nx
RU16vvxEszYbtRhrI1d1+VSO8ROFPXQNrT5oQtxOpApuawNMZY12WwE79EUhqQAxokouc83MYvyl
WJj6SI3rq0jWxDIL0Ox8PK8xXhFuqqYcymwARsUIlnM6z2nOZKJkMnktYgi/ajQ21B8ekYI7fdZp
0FCsDaeRxaWUn4NEb9Ud0yNxPKj6//HH/wBiSade
===END CRASH DUMP===

**Comment by DaPigGuy** [comment]
Not a PiggyCE or MysteryCrates issue. Check configuration of your crates.

**Comment by mikeygio10** [comment]
Theres no error I could send

**Comment by DaPigGuy** [comment]
The issue is with your crate config
