### ISSUE TITLE
ayuda PiggyCE no funciona con MysteryCrates

### ISSUE THREAD

**Issue by Dexus18** [DaPigGuy/PiggyCustomEnchants#247]
intente de todas las formas pero no es compatible con MysteryCrates porque cada ves intento ponerlo se crashea. ejemplo:
común:
    gotas:
      - nombre: "§a§lG Sword§r"
        id: 276
        meta: 20
        cantidad: 1
       *** encantamientos:
             veneno:
               nivel 5 ***
        Conocimiento: "Poder"
      - id: 366
        meta: 60
        cantidad: 16
      - id: 264
        meta: 20
        cantidad: 3
    bloque: "173: 0"
    transmitir:
      habilitar: verdadero
      comando: "say \"% PLAYER% \ "está abriendo Common Crate en / crates"
      necesito ayuda :(

**Comment by Aericio** [comment]
Configuration should remain in English.
