### ISSUE TITLE
Doesnt work on genysis

### ISSUE THREAD

**Issue by PvPsaturN** [DaPigGuy/PiggyCustomEnchants#25]
Hi
@DaPigGuy is there possible chance that u could make these plugin to genysis server it would be great 
Thank you if u can

**Comment by QuiverlyRivalry** [comment]
#13

**Comment by PvPsaturN** [comment]
#13 what?

**Comment by PvPsaturN** [comment]
Can u download spoon on andriod?

**Comment by QuiverlyRivalry** [comment]
What device are you using to host?

**Comment by PvPsaturN** [comment]
Genysis

**Comment by QuiverlyRivalry** [comment]
No device
Like VPS,
Computer,
Phone,
Tablet,
Server

**Comment by PvPsaturN** [comment]
Oh sorry a phone

**Comment by QuiverlyRivalry** [comment]
Just go on YouTube search How to make Pocketmine server on android
