### ISSUE TITLE
Outdated MysteryCrates version.

### ISSUE THREAD

**Issue by Dexus18** [DaPigGuy/PiggyCustomEnchants#251]
install piggyCE 2.0.4 and MysteryCrates 9.1.1 and they remain incompatible help
I officially downloaded them and they are the only plugins I have and they don't work.
I try to open the common chest and the server closes (I haven't touched anything)
I opened it without configuring anything, could you tell me if it is configured or something like that because this problem takes time and maybe I am not the only.

 common:
    drops:
      - name: "§a§lG Sword§r"
        id: 276
        meta: 0
        amount: 1
        enchantments:
          protection:
            level: 3
        lore: "OP Sword\nFire Blade"
      - id: 366
        meta: 0
        amount: 16
    block: "173:0"
    broadcast:
      enable: true
      command: "say \"%PLAYER%\" is opening Common Crate at /crates"

I repeat I have not touched anything I started when I download it and it does not work (they are the latest versions of the plugins) please I need to explain how this is going.

**Comment by Aericio** [comment]
Issue should be reported to JackMD/MysteryCrates

**Comment by Dexus18** [comment]
like what obsolete version? if it is the last and official

**Comment by Aericio** [comment]
Also, stop creating new issues for the same thing.

**Comment by Dexus18** [comment]
ok

**Comment by Aericio** [comment]
You can build the plugin yourself with DevTools and DeVirion. If you don't know how, then wait for @JackMD to submit a release.

Also #250, you might need to connect your GitHub account to poggit to download the dev builds.

**Comment by Dexus18** [comment]
OK thank you very much
