### ISSUE TITLE
Bigg fat issue

### ISSUE THREAD

**Issue by darkadams** [DaPigGuy/PiggyCustomEnchants#252]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

- OS:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

So this is the problem basically the enchant poison cloud can hurt even ur ally's. My friend put poison cloud on his gear and we  allied each other but his poison cloud can still dmg me.

**Comment by Aericio** [comment]
We don't have support for faction plugins.
