### ISSUE TITLE
Suggestion to avoid lag

### ISSUE THREAD

**Issue by darkadams** [DaPigGuy/PiggyCustomEnchants#253]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

- OS:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

I was wondering if u can let us config and disable some enchants players cant use or get in game because it causes lag such as force field. Also make it so we can set a limit for all enchants. For example lifesteal I want to make the enchant limit to 2 so they can only get levels 1 and 2 of lifesteal.

**Comment by DaPigGuy** [comment]
https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/resources/config.yml#L17
