### ISSUE TITLE
Re-upload to MCBBS

### ISSUE THREAD

**Issue by 1137305770** [DaPigGuy/PiggyCustomEnchants#259]
Hi author!
The PiggyCustomEnchants and PiggyCustomEnchantsShop Plugins is great，could I reproduce the files to mcbbs? I marked you as the author in the MCBBS，Users download the files in your original github or poggit .

**Comment by Aericio** [comment]
Under the Apache License 2.0, you are allowed to distribute the plugin.

However, please wait until we release v2.1.0 (#257) before you make your post since there are some important changes.
