### ISSUE TITLE
Enchants Changing ⚠️

### ISSUE THREAD

**Issue by VpsOP** [DaPigGuy/PiggyCustomEnchants#263]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Version:**

- PiggyCustomEnchants:

- PMMP:

- OS:

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Everytime i restart the server ce ids chages and so the Enchants on the items.

![Screenshot_2020-03-01-02-44-43-270_com mojang minecraftpe](https://user-images.githubusercontent.com/57450981/75615203-ee3d2d80-5b66-11ea-8fcb-2580301d7d7b.jpg)

This was driller 5 enchant and now its healing 5

**Comment by VpsOP** [comment]
It's not invalid ce ids are changing want me to send more ss? Or a vid?

**Comment by DaPigGuy** [comment]
Show /plugins

**Comment by VpsOP** [comment]
Ok

**Comment by VpsOP** [comment]
![Uploading Screenshot_2020-03-01-10-40-42-747_com.mojang.minecraftpe.jpg…]()

![Screenshot_2020-03-01-10-40-33-778_com mojang minecraftpe](https://user-images.githubusercontent.com/57450981/75619992-3bda8a00-5ba9-11ea-9f29-a63d13c19813.jpg)
![Screenshot_2020-03-01-10-38-26-574_com mojang minecraftpe](https://user-images.githubusercontent.com/57450981/75619993-4006a780-5ba9-11ea-867d-1fb680308e30.jpg)
![Screenshot_2020-03-01-10-38-03-561_com mojang minecraftpe](https://user-images.githubusercontent.com/57450981/75619996-439a2e80-5ba9-11ea-8258-32d2185bbea8.jpg)

See i reloaded server 3 times and enchnat id of cactus changes

**Comment by VpsOP** [comment]
![Screenshot_2020-03-01-10-40-42-747_com mojang minecraftpe](https://user-images.githubusercontent.com/57450981/75620008-69bfce80-5ba9-11ea-9cfc-e23f5ca6ddf7.jpg)

All plugins

**Comment by Aericio** [comment]
I am unable to reproduce this issue. Can you try to re-download PiggyCustomEnchants from Poggit?
