### ISSUE TITLE
3.0.0-ALPHA7 bug.

### ISSUE THREAD

**Issue by xXSirGamesXx** [DaPigGuy/PiggyCustomEnchants#27]
`[12:16:02] [Server thread/CRITICAL]: Error: "Undefined class constant 'RARITY_COMMON'" (EXCEPTION) in "plugins/PiggyCustomEnchants-master/src/PiggyCustomEnchants/Main" at line 233`
This happens on startup and causes plugin to crash.

**Comment by DaPigGuy** [comment]
Please use the master branch of PMMP...

**Comment by DaPigGuy** [comment]
And fill out the information...

**Comment by xXSirGamesXx** [comment]
Is there a template?

**Comment by Aericio** [comment]
There is not. @DaPigGuy, Idiot. I'll add them.
