### ISSUE TITLE
Items cannot be enchanted with books.

### ISSUE THREAD

**Issue by KriskotooBG** [DaPigGuy/PiggyCustomEnchants#270]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title (i.e "Poison enchant does not apply effect")

### Issue Description

- Expected result: When item is placed on a book, as said in the README, the item should get the enchant and the book removed from the player's inventory.
- Actual result: Book and item just swap, without any action.

#### Steps to Reproduce the Issue
1. Use /ce enchant <ench> <lvl> on a book
2. Try to apply that book to an item.

### OS and Versions

* PocketMine-MP: PocketMine-MP 3.11.2 (protocol 389)
* PiggyCustomEnchants: 2.1.2
* PHP: 7.2
* Server OS: Windows 10 home (PC)

### Extra Information

**Comment by DaPigGuy** [comment]
Can't reproduce the issue. https://streamable.com/gmlvn
