### ISSUE TITLE
CE Activation Cooldown

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyCustomEnchants#271]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description

I already tried adding a cool down to blind in the extradata file or what ever its called and it just doesnt seem to work, does it not support a cooldown and if so can you add it? because players get permanent blindness when they pvp against someone with the blind CE and its just too over powered
### Extra Information

**Comment by CaptainHatchet** [comment]
Not permanent blindness, runs out after a while. Try updating your version.

**Comment by PsychoPE** [comment]
I am using the most recent build, its not permanent so to speak but when you are pvping with someone and they are constantly hitting you it is pretty much infinite blindness they arent just going to stop fighting you cause you’re blind they will keep hitting you till you die, would be good if cooldown was working without so if they hit someone once they get blindness then they have like a 15 second cool down or something then blindness will take effect again
