### ISSUE TITLE
Add a way to disable enchanting items on book drop

### ISSUE THREAD

**Issue by xBeastMode** [DaPigGuy/PiggyCustomEnchants#274]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
I don't like the idea of having items automatically enchanted when an enchanted book is dropped on it. I have my own system for applying custom enchantments and that just ruins it. I have modified the plugin to disable this, but I'd still like to see this very simple feature added in the config file.
### Extra Information

**Comment by DaPigGuy** [comment]
Please test the latest build

**Comment by xBeastMode** [comment]
That was fast. Thanks, kind sir 😄
