### ISSUE TITLE
CEBook Probability Rates

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyCustomEnchants#276]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description
Enchant rates is a chance that you have of successfully enchanting your item and a chance that you destroy the enchant upon trying to add it to your item, when you buy a CEBook from /ceshop the book should come with a random Success rate and a random Destroy rate, both of these figures would be shown on the lore of the book before trying to enchant, to make it more interested the rates should be random from 0 to 100% so you could have 0% success all the way up to 100% same for destroy rate.

Example:

Blind 1
Success Rate 37%
Destroy Rate 63%
(this part isnt needed but would also be useful to new players)
Has a chance to give blindness to the player
### Extra Information

**Comment by minijaham** [comment]
Or make /combine command(also probability rates >:)
When doing /combine, you have to hold an enchantment book
And when you execute it, you have to hold an item to enchant

Btw Global enchantments can be enchanted on a freaking block lmao 
Now I have a cobblestone with Lucky Charm III

**Comment by DaPigGuy** [comment]
This does not seem like something that should be added directly into PiggyCE. You can however disable PiggyCE's enchantment books and reimplement them in a separate plugin.
