### ISSUE TITLE
Easy way to make enchants

### ISSUE THREAD

**Issue by PsychoPE** [DaPigGuy/PiggyCustomEnchants#277]
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
Have a part in the config where we can create our own custom enchants, this would be useful for those who dont know how to code but want to add their own ideas to it.

Example:
```
newenchants:
  Name: Angelic
  Effects:
  - Levitation
  - Hunger
  Chance: 20
  Duration: 3 (seconds)
  Description: Has a chance to give hunger and levitation to a player
```

etc and what ever other information would be needed ofc
### Extra Information

**Comment by VoltageMC** [comment]
When you realize making enchants isnt that hard in the source code

**Comment by PsychoPE** [comment]
> When you realize making enchants isnt that hard in the source code

Yes but this is for people that have no idea how to code

**Comment by DaPigGuy** [comment]
This will be implemented in a separate plugin.

**Comment by DaPigGuy** [comment]
Use https://github.com/Aericio/PCEEasyEnchants
