### ISSUE TITLE
Fix enchantments!

### ISSUE THREAD

**Issue by arkhamservers** [DaPigGuy/PiggyCustomEnchants#278]
Explosion 1-5 when mining near an NPC "slapper" it will open all slappers in a radius from you, this doesn't happen every time but it is annoying. it would be great if it were fixed.

Also 
Wither Skull : is broken when firing the bow the wither skull crashed the game.

**Comment by Aericio** [comment]
> Explosion 1-5 when mining near an NPC "slapper" it will open all slappers in a radius from you, this doesn't happen every time but it is annoying. it would be great if it were fixed.

Will be added to PCEAllyChecks.

> Wither Skull : is broken when firing the bow the wither skull crashed the game.

Unable to reproduce.

**Comment by Aericio** [comment]
Download PCEAllyChecks: https://poggit.pmmp.io/ci/Aericio/PCEAllyChecks/PCEAllyChecks/

Slapper support has been added in v1.0.1.
