### ISSUE TITLE
Cactus Enchantment Activates Slappers

### ISSUE THREAD

**Issue by Johnsonk79** [DaPigGuy/PiggyCustomEnchants#281]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title (i.e "Poison enchant does not apply effect")

### Issue Description

- Expected result: What were you expecting to happen?

Cactus Enchantment does not activate slappers

- Actual result: What actually happened?

Cactus Enchantment activates and spams slappers

#### Steps to Reproduce the Issue

1. Get the Cactus enchantment on your armor and wear it
2. Go close to a slapper that has commands assigned

**Comment by Aericio** [comment]
Download https://poggit.pmmp.io/p/PCEAllyChecks
