### ISSUE TITLE
Vampire Enchants internal server error

### ISSUE THREAD

**Issue by minijaham** [DaPigGuy/PiggyCustomEnchants#287]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title (i.e "Poison enchant does not apply effect")

Link to crashdump: 
15.04 18:00:07 [Server] Server thread/CRITICAL ErrorException: "Undefined index: cooldown" (EXCEPTION) in "plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/weapons/VampireEnchant" at line 36
15.04 18:00:07 [Server] Server thread/DEBUG #0 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/weapons/VampireEnchant(36): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[25] Undefined index: cooldown, string[155] phar:///plugins/PiggyCustomEnchant, integer 36, array[7])
15.04 18:00:07 [Server] Server thread/DEBUG #1 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/traits/ReactiveTrait(49): DaPigGuy\PiggyCustomEnchants\enchants\weapons\VampireEnchant->react(object pocketmine\Player, object pocketmine\item\Sword, object pocketmine\inventory\PlayerInventory, integer 0, object pocketmine\event\entity\EntityDamageByEntityEvent, integer 1, integer 1)
15.04 18:00:07 [Server] Server thread/DEBUG #2 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/enchants/traits/ReactiveTrait(135): DaPigGuy\PiggyCustomEnchants\enchants\ReactiveEnchantment->onReaction(object pocketmine\Player, object pocketmine\item\Sword, object pocketmine\inventory\PlayerInventory, integer 0, object pocketmine\event\entity\EntityDamageByEntityEvent, integer 1, integer 1)
15.04 18:00:07 [Server] Server thread/DEBUG #3 plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/EventListener(160): DaPigGuy\PiggyCustomEnchants\enchants\ReactiveEnchantment::attemptReaction(object pocketmine\Player, object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/MethodEventExecutor(42): DaPigGuy\PiggyCustomEnchants\EventListener->onDamage(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object DaPigGuy\PiggyCustomEnchants\EventListener, object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #6 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #7 src/pocketmine/entity/Entity(925): pocketmine\event\Event->call()
15.04 18:00:07 [Server] Server thread/DEBUG #8 src/pocketmine/entity/Living(545): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #9 src/pocketmine/Player(3690): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #10 src/pocketmine/Player(2570): pocketmine\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent)
15.04 18:00:07 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(150): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
15.04 18:00:07 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(178): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
15.04 18:00:07 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.04 18:00:07 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
15.04 18:00:07 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
15.04 18:00:07 [Server] Server thread/DEBUG #16 src/pocketmine/Player(3100): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.04 18:00:07 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
15.04 18:00:07 [Server] Server thread/DEBUG #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 68.7.150.203 64852, object raklib\protocol\EncapsulatedPacket, integer 0)
15.04 18:00:07 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
15.04 18:00:07 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
15.04 18:00:07 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
15.04 18:00:07 [Server] Server thread/DEBUG #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
15.04 18:00:07 [Server] Server thread/DEBUG #23 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1586973606.8412)
15.04 18:00:07 [Server] Server thread/DEBUG #24 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
15.04 18:00:07 [Server] Server thread/DEBUG #25 src/pocketmine/Server(1584): pocketmine\Server->start()
15.04 18:00:07 [Server] Server thread/DEBUG #26 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
15.04 18:00:07 [Server] Server thread/DEBUG #27 src/pocketmine/PocketMine(296): pocketmine\server()
15.04 18:00:07 [Server] Server thread/DEBUG #28 (11): require(string[107] phar:///PMMP-Latest-Stable.phar/sr)

### Extra Information
Vampire enchant crashes the player upon activating

**Comment by DaPigGuy** [comment]
Try build #439 at https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants/~
