### ISSUE TITLE
deepwounds enchant causes internal server error apon use

### ISSUE THREAD

**Issue by TheUtopianPlayz** [DaPigGuy/PiggyCustomEnchants#289]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title (i.e "Poison enchant does not apply effect")

Link to crashdump:  https://hastebin.com/kiwexedami.coffeescript

### Extra Information
when u hit a player with an item that has the deepwounds enchant it kicks them for an internal server error

**Comment by Aericio** [comment]
Try build #439 at https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants/ ~

**Comment by DaPigGuy** [comment]
Using an outdated version of PiggyCE.

**Comment by DaPigGuy** [comment]
Never mind 😅

**Comment by DaPigGuy** [comment]
Try the latest build
