### ISSUE TITLE
CE Limit

### ISSUE THREAD

**Issue by owenraihan** [DaPigGuy/PiggyCustomEnchants#290]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description
A new feature which lets people have max CE in each tools/armor/weapons/globals, limit of CE can be configure in config.yml!

### Extra Information
None

**Comment by Aericio** [comment]
This feature has been requested before. Limits are not the job of PiggyCustomEnchants but rather the plugin you are using to give enchants.

For more information, please read https://github.com/DaPigGuy/PiggyCustomEnchantsShop/issues/31

**Comment by pleasepoggitwork** [comment]
Aericio what about PCEBookShop :'))
