### ISSUE TITLE
when enchant i get kicked

### ISSUE THREAD

**Issue by davelny** [DaPigGuy/PiggyCustomEnchants#293]
Argument 1 passed to DaPigGuy\PiggyCustomEnchants\utils\Utils::getTFConstFromString() must be of the type string, null given, called in phar://C:/Users/davie/Desktop/server/plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/utils/Utils.php on line 217" (EXCEPTION) in "plugins/PiggyCustomEnchants.phar/src/DaPigGuy/PiggyCustomEnchants/utils/Utils" at line 220

**Comment by DaPigGuy** [comment]
Can you please show your PiggyCustomEnchants config?

**Comment by davelny** [comment]
ok

**Comment by davelny** [comment]
how do i get there

**Comment by davelny** [comment]
it doent let me send it so i well send the file

**Comment by davelny** [comment]
[PiggyCustomEnchants.zip](https://github.com/DaPigGuy/PiggyCustomEnchants/files/4549761/PiggyCustomEnchants.zip)

**Comment by davelny** [comment]
is the zip file ok

**Comment by davelny** [comment]
hello

**Comment by davelny** [comment]
can u fix this asap

**Comment by owenraihan** [comment]
u deleted some code in code u should delete the config and it will generate a new config. What you trying to do by the way?

**Comment by owenraihan** [comment]
config*

**Comment by davelny** [comment]
I am trying to make a survival world with my freinds with behavior packs
and plugins

**Comment by davelny** [comment]
Thx for helping me fix it

**Comment by owenraihan** [comment]
np
