### ISSUE TITLE
Hallucination bug

### ISSUE THREAD

**Issue by pleasepoggitwork** [DaPigGuy/PiggyCustomEnchants#294]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [X] Have a detailed title (i.e "Poison enchant does not apply effect")

### Issue Description

- Expected result: What were you expecting to happen?
Previously placed blocks to either be non breakable while a player is hallucinating, and to not override and blocks in the way of the hallucination blocks.
- Actual result: What actually happened?
The blocks in the way get overridden, and players can glitch into bases.
#### Steps to Reproduce the Issue
1. ... Get a wall
2. ... Hit somebody untill they are hallucinating
3... Walk against the where the wall would be, and wait for hallu to disapear
4... You should go through the wall

### OS and Versions

* PocketMine-MP:
* PiggyCustomEnchants:
* PHP:
* Server OS:

### Extra Information

**Comment by DaPigGuy** [comment]
Can't reproduce the issue.
