### ISSUE TITLE
Language of enchanted items not translated client side

### ISSUE THREAD

**Issue by benda95280** [DaPigGuy/PiggyCustomEnchants#296]
Please make sure your issue complies with these guidelines:
- * [X] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [X] Issue must have not been reported previously
- * [X] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [X] Have a detailed title (i.e "Poison enchant does not apply effect")

### Issue Description

- Expected result: Item shown in language of the client
- Actual result: Item is in english

#### Steps to Reproduce the Issue
1. Apply enchant and give to player :
`$item->addEnchantment(new EnchantmentInstance(CustomEnchantManager::getEnchantment($randedEnchantID), $enchantLevel));`

### OS and Versions

* PocketMine-MP: 3.12.0
* PiggyCustomEnchants: 2.1.7
* PHP: 7.3.8
* Server OS: Windows 10 1909

### Extra Information
Example with French-English
![Example French/English](https://user-images.githubusercontent.com/1539408/81481847-2df15700-9233-11ea-9f63-2a2ad0920c1a.png)

**Comment by benda95280** [comment]
No information about this ?

**Comment by DaPigGuy** [comment]
It's currently not implemented.

**Comment by benda95280** [comment]
Any idea why it happen ?
