### ISSUE TITLE
Enchantment Suggestion

### ISSUE THREAD

**Issue by hashimthebeast** [DaPigGuy/PiggyCustomEnchants#301]
This plugin is amazing I love it. I have one suggestion that I would really love to see added. Its an enchantment called Kaboom. It basically acts like a single block of tnt explosion on the player (without the tnt) and this is what it looks like (https://www.youtube.com/watch?v=VNifvXHMTGM&feature=youtu.be) The first one shown was a double activation. This is kaboom level 2 and level 3 isnt much stronger than this but activates more frequently.

**Comment by DaPigGuy** [comment]
We currently are not adding new enchantments.
