### ISSUE TITLE
enchant disable feature

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyCustomEnchants#310]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description

Add a "disabled.yml" which disables enchantments

### Extra Information

**Comment by Aericio** [comment]
What a great feature, so glad it already exists.

https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/resources/config.yml#L19

**Comment by jaylac2000** [comment]
aha, tyty, i didnt even notice that
