### ISSUE TITLE
add /ce remove

### ISSUE THREAD

**Issue by jaylac2000** [DaPigGuy/PiggyCustomEnchants#312]
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Extra Information

add "/ce remove <enchant> from your items where it costs money (set in config) so that people can remove custom enchants off of their items

**Comment by minijaham** [comment]
Maybe...code it on your own?

Use EconomyAPI::getInstance()->reduceMoney()
