### ISSUE TITLE
I NEED HELP LOL

### ISSUE THREAD

**Issue by x-lIlIlIlIl** [DaPigGuy/PiggyCustomEnchants#313]
Please make sure your issue complies with these guidelines:
- * [YEA OFFICAL ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ IM NOT SURE] Issue must have not been reported previously
- * [CHECK ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [CHECK ] Have a detailed title.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...
2. ...

### OS and Versions

* PocketMine-MP:
* PiggyCustomEnchants:
* PHP:
* Server OS:

https://crash.pmmp.io/view/4414828

**Comment by jaylac2000** [comment]
what do you need help with? this does not provide any or the correct information and may be closed...
