### ISSUE TITLE
add a enchant limy!

### ISSUE THREAD

**Issue by x-lIlIlIlIl** [DaPigGuy/PiggyCustomEnchants#315]
Hello! i wanted to make a suggestion for this very awesome plugin soo i was thinking you guys could add a limt for enchants because ive seen players on my servers with like 6-20 enchants on there armour/swords and it becomes way to unfair for other players it even crashes the server some times to do to some enchants so if you could add a limt for enchants that would be AMAZING!! thanks have a good day -false :)

**Comment by DaPigGuy** [comment]
Duplicate of #290
