### ISSUE TITLE
Ban World

### ISSUE THREAD

**Issue by mrpwes** [DaPigGuy/PiggyCustomEnchants#317]
config.yml

This is Used to Ban Commands in only the Worlds Below.
Worlds: ["bannedworld1", "bannedworld2"] # You can add as Many as needed

~~Like CustomShopUI

**Comment by Aericio** [comment]
Did you even read check the configuration?

https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/resources/config.yml#L18-L23
