### ISSUE TITLE
Crash with piggy custom enchant shop 

### ISSUE THREAD

**Issue by BlackAngels56** [DaPigGuy/PiggyCustomEnchants#319]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title.

Link to crashdump: https://hastebin.com/oqorokaqej.cs

### Extra Information

**Comment by Aericio** [comment]
Poggit was down.
