### ISSUE TITLE
Unhandled exception executing command 'ce enchant Missile' in customenchant: Return value of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getId() must be of the type integer, null returned

### ISSUE THREAD

**Issue by teracube** [DaPigGuy/PiggyCustomEnchants#32]
Please make sure your issue complies with these guidelines:
- * [x ] Be using PMMP
- * [x] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title like "CustomEnchants::getName() must be..."
- * [x] Provide any crash dumps or errors

#### **General**
critical error repeating
Server thread/CRITICAL]: Unhandled exception executing command 'ce enchant Missile' in customenchant: Return value of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getId() must be of the type integer, null returned 2017-08-11 [11:30:47] [Server thread/CRITICAL]: TypeError: "Return value of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getId() must be of the type integer, null returned" (EXCEPTION) in "PiggyCustomEnchants.phar/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants" at line 147

#### **Version of PiggyCustomEnchants:**
Dev 74
https://poggit.pmmp.io/r/9951/PiggyCustomEnchants.phar

Thanks

**Comment by optimusprime338** [comment]
@DaPigGuy  fix this please!
