### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ElementalMinecraftGaming** [DaPigGuy/PiggyCustomEnchants#320]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title.

### Issue Description

- Expected result: For the plugin to load
- Actual result: Error file attached

#### Steps to Reproduce the Issue
1.load up the plugin
[error.txt](https://github.com/DaPigGuy/PiggyCustomEnchants/files/5002489/error.txt)

### OS and Versions

* PocketMine-MP: 3.14.2
* PiggyCustomEnchants: V2.3.0
* PHP: 7.3
* Server OS: Windows

### Extra Information

**Comment by Aericio** [comment]
Check folder permissions.
