### ISSUE TITLE
Config line 19

### ISSUE THREAD

**Issue by LuCaTiLe41** [DaPigGuy/PiggyCustomEnchants#327]
![Screenshot_20201102-205929](https://user-images.githubusercontent.com/68434738/97872381-e61a3b00-1d50-11eb-938d-ea140355de4e.png)

Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title.

Link to crashdump: 

### Extra Information

**Comment by Aericio** [comment]
What's the error? Send both the error and the config.
