### ISSUE TITLE
crouching while using jettpack with empty fuel crashes the server

### ISSUE THREAD

**Issue by TheUtopianPlayz** [DaPigGuy/PiggyCustomEnchants#332]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title.

Link to crashdump: https://crash.pmmp.io/view/4705781

### Extra Information 
pretty much as the title says, when ever u try to use jetpack while ur fuel is empty it causes the server to crash, im on the latest stable version of pmmp

**Comment by Aericio** [comment]
I also added a cooldown to prevent an issue where spamming shift key would allow you to infinitely fly.

If you feel that the cooldown is too long (default is 25), go to `extra_data.json` and modify `jetpack.enableAmount`.
