### ISSUE TITLE
Lower Forcefield CE Affect

### ISSUE THREAD

**Issue by GitAndrew7** [DaPigGuy/PiggyCustomEnchants#335]
Hello! This isn’t much of an issue but a problem for me and maybe many other people. I think that the forcefield ce affect should be lessened. More into detail, all the ce run smoothly for me but the forcefield. The forcefield lags my game out, it’s still playable but it lags me and people around me. I think this can be fixed by making it use less affects. Besides that I really enjoy the plug-in you guys created. Thanks and have a good day.

**Comment by Aericio** [comment]
Change `radiusMultiplier` in `extra_data.json` to reduce the forcefield effect.
```
    "forcefield": {
        "radiusMultiplier": 0.75
    },
```
