### ISSUE TITLE
permanent Grow/Shrink Enchant

### ISSUE THREAD

**Issue by Austere-Zero** [DaPigGuy/PiggyCustomEnchants#341]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Return to normal size on removal or second use of Grow/Shrink enchant.
- Actual result: What actually happened?
- Remained permanent in the shrink/growth until leaving server

#### Steps to Reproduce the Issue
1. ...put on any full armor with grow or shrink.
2. ...crouch again or take off armor 

### OS and Versions

* PocketMine-MP:latest
* PiggyCustomEnchants:Latest
* PHP:
* Server OS: 12gb ram hosting

### Extra Information

**Comment by Aericio** [comment]
there are some changes with grow/shrink now

- add shrink/grow power remaining tip
- add shrink/grow cooldown time tip
- untoggling shrink/grow will prevent you from toggling it again until cooldown runs out. cooldown can be modified in `cooldowns.json`
