### ISSUE TITLE
My suggestion

### ISSUE THREAD

**Issue by MrNinja008** [DaPigGuy/PiggyCustomEnchants#343]
Please make sure your issue complies with these guidelines:
- * [ ] Pls Add Support To Netherite Plugin made by Wertzui!
- * [ ] Be detailed on what you want & make sure the idea is plausible
 I am using Netherite Plugin made by Wertzui sadly i cant use custom enchants in Netherite pls add support to it on next update! Pls.

### Extra Information

**Comment by Aericio** [comment]
Not supporting third-party plugins.

**Comment by MrNinja008** [comment]
Bro Or make a Netherite Plugin yourself and give support to Piggycustom enchants then it will be not third party.

**Comment by Aericio** [comment]
Support will only be added when PMMP adds netherite armor. Not if an external plugin adds netherite armor.
