### ISSUE TITLE
Soul Bound Not working

### ISSUE THREAD

**Issue by IcyEndymion004** [DaPigGuy/PiggyCustomEnchants#344]
So i have been seeing in testing if you die with soul bound on armor that is equipped it wont work but with other things just in your inventory it works anyone know why?

**Comment by IcyEndymion004** [comment]
just let me know if you need more info or a video im in the discord so just ping me and ill make sure to look

**Comment by IcyEndymion004** [comment]
Also this happended
02.06 19:09:34 [Server] CRITICAL TypeError: "Return value of pocketmine\entity\Living::getArmorInventory() must be an instance of pocketmine\inventory\ArmorInventory, null returned" (EXCEPTION) in "pmsrc/src/pocketmine/entity/Living" at line 433
02.06 19:09:34 [Server] CRITICAL #0 plugins/PiggyCustomEnchants (4).phar/src/DaPigGuy/PiggyCustomEnchants/EventListener(111): pocketmine\entity\Living->getArmorInventory()
02.06 19:09:34 [Server] CRITICAL #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): DaPigGuy\PiggyCustomEnchants\EventListener->onArmorChange(object pocketmine\event\entity\EntityArmorChangeEvent)
02.06 19:09:34 [Server] CRITICAL #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object DaPigGuy\PiggyCustomEnchants\EventListener, object pocketmine\event\entity\EntityArmorChangeEvent)
02.06 19:09:34 [Server] CRITICAL #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\EntityArmorChangeEvent)
02.06 19:09:34 [Server] CRITICAL #4 pmsrc/src/pocketmine/inventory/ArmorInventoryEventProcessor(40): pocketmine\event\Event->call()
02.06 19:09:34 [Server] CRITICAL #5 pmsrc/src/pocketmine/inventory/BaseInventory(168): pocketmine\inventory\ArmorInventoryEventProcessor->onSlotChange(object pocketmine\inventory\ArmorInventory, integer 0, object pocketmine\item\ItemBlock, object pocketmine\item\ItemBlock)
02.06 19:09:34 [Server] CRITICAL #6 plugins/PiggyCustomEnchants (4).phar/src/DaPigGuy/PiggyCustomEnchants/enchants/miscellaneous/SoulboundEnchant(43): pocketmine\inventory\BaseInventory->setItem(integer 0, object pocketmine\item\ItemBlock)
02.06 19:09:34 [Server] CRITICAL #7 pmsrc/src/pocketmine/scheduler/ClosureTask(61): DaPigGuy\PiggyCustomEnchants\enchants\miscellaneous\SoulboundEnchant->DaPigGuy\PiggyCustomEnchants\enchants\miscellaneous\{closure}(integer 211686)
02.06 19:09:34 [Server] CRITICAL #8 pmsrc/src/pocketmine/scheduler/TaskHandler(137): pocketmine\scheduler\ClosureTask->onRun(integer 211686)

**Comment by DaPigGuy** [comment]
Could not reproduce on PR #169
