### ISSUE TITLE
Question about enchanting in slots

### ISSUE THREAD

**Issue by EpicPinkCreeper** [DaPigGuy/PiggyCustomEnchants#35]
Hello! Is there is a command to enchant objects in certain slots? I saw something about that in the API documentation, but if there is an actual in game command I don't know what it is.  Sorry, this isn't an issue but I am not sure where I should put it.

**Comment by Aericio** [comment]
Just select the item and use /ce...

**Comment by DaPigGuy** [comment]
@Aericio **API documentation** He's talking about the how to do it with the CE api

**Comment by DaPigGuy** [comment]
@EpicPinkCreeper `$item = $player->getInventory->getItem(0); //$player is the player
$ce = $this->getServer()->getPluginManager()->getPlugin("PiggyCustomEnchants");
$ce->addEnchantment($item, ["Porkified", "Grappling"], [3, 1], $check) //Enchants and level can be arrays or one specific value. Check arguments is not needed unless you would like to override checks (set to true). Enchant names, ids, or classes can be used.
$player->getInventory()->setItem(0, $item);`

**Comment by DaPigGuy** [comment]
There is no command to enchant an item in a certain slot.
