### ISSUE TITLE
Drillier and anti knockback

### ISSUE THREAD

**Issue by silliershark** [DaPigGuy/PiggyCustomEnchants#355]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

#### Steps to Reproduce the Issue
1. ...anti knockback not working
2. ...drillier not working

### OS and Versions

* PocketMine-MP:
* PiggyCustomEnchants:
* PHP:
* Server OS:

### Extra Information

**Comment by Aericio** [comment]
Fixed in https://github.com/DaPigGuy/PiggyCustomEnchants/pull/369
