### ISSUE TITLE
Please help me, I am having problem with PiggyCustomEnchants plugin This is the error message I get when I start the server:

### ISSUE THREAD

**Issue by NhanAZ** [DaPigGuy/PiggyCustomEnchants#357]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title.

Link to crashdump: 

### Extra Information
https://hastebin.com/oqerowotud.yaml

**Comment by Arthur-iv-studios** [comment]
@NhanAZ Ayo If You Forked my Old 3D Weapon Bow That suprizeingly doesnt load the 3d gun, Fork This One https://github.com/Arthur-iv-studios/3D-Bow-Gun/ its a fix version
