### ISSUE TITLE
players use boots Jetpack: Enable flying / server properties allow-flight=off

### ISSUE THREAD

**Issue by teracube** [DaPigGuy/PiggyCustomEnchants#36]
Hi,
Thanks fot this great plugin.
The players of my server use boots to fly while the server  properties  allow-flight=off
How to set up disable use boots jet pack ?
thanks

sorry for my bad english

**Comment by QuiverlyRivalry** [comment]
You can maybe ban the command or disable flight?

**Comment by PvPsaturN** [comment]
What is the command to use CUSTOM ENCHANT

**Comment by DaPigGuy** [comment]
@PvPsaturN /ce

**Comment by Aericio** [comment]
> The players of my server use boots to fly while the server properties allow-flight=off

The only method I am aware of is just to set `allow-flight=on`, @DaPigGuy could implement a way ce items to bypass fly, but it's probably better just to set it to on to prevent glitching. I don't know what to say about hackers, though. ¯\_(ツ)_/¯
