### ISSUE TITLE
Glowing and Jetpack

### ISSUE THREAD

**Issue by SPMP2** [DaPigGuy/PiggyCustomEnchants#370]
Netherite doesn’t work (helmet & boots)
Plugin version 2.4.4
Api 3.25.1

**Comment by TheGamingSnail** [comment]
Netherite isn't in base pmmp and so there is no reason it has to be compatible with pce.

**Comment by TheGamingSnail** [comment]
*has to be

**Comment by SPMP2** [comment]
Ok bro like you want xD i have fixed custom enchant and netherite in your plugin to my server 🥲😂
