### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Luis19028** [DaPigGuy/PiggyCustomEnchants#373]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title.

Link to crashdump: 
https://www.toptal.com/developers/hastebin/ocaheyoxov.csharp

### Extra Information

**Comment by Aericio** [comment]
dead link
