### ISSUE TITLE
Nested permission declarations are no longer supported.

### ISSUE THREAD

**Issue by ChaotiqueSlime** [DaPigGuy/PiggyCustomEnchants#376]
Could not load plugin '/plugins/PiggyCustomEnchants-master': Invalid plugin manifest: Invalid Plugin "permissions": Nested permission declarations are no longer supported. Declare each permission separately.

i believe this is in plugin.yml can someone fix it?

**Comment by Aericio** [comment]
Fixed in https://github.com/DaPigGuy/PiggyCustomEnchants/pull/369
