### ISSUE TITLE
Doesn't Exist

### ISSUE THREAD

**Issue by Tuvqlu** [DaPigGuy/PiggyCustomEnchants#379]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen?
New enchants and /ce command
- Actual result: What actually happened?
Nothing 
#### Steps to Reproduce the Issue
1. Fix
2. This

### OS and Versions

* PocketMine-MP: 4.1.0
* PiggyCustomEnchants: 2.4.6
* PHP: 4.0.0
* Server OS: BisectHosting

### Extra Information

**Comment by Aericio** [comment]
PiggyCustomEnchants doesn't support PM 4.x yet
