### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyCustomEnchants#38]
Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getEnchantment(int $id) should be compatible with pocketmine\item\enchantment\Enchantment::getEnchantment($id)" (EXCEPTION) in "PiggyCustomEnchants.phar/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants" at line 136

**Comment by DaPigGuy** [comment]
Please fill in the information.
