### ISSUE TITLE
Unable to move items in your inventory if they have a CE on them

### ISSUE THREAD

**Issue by ErosionYT** [DaPigGuy/PiggyCustomEnchants#380]
### Issue Description

- Expected result: Be able to move the item with the enchant around in your inventory
- Actual result: Item with the enchant gets stuck in the slot you enchantened it in

#### Steps to Reproduce the Issue
1. enchant a pickaxe with any ce (thats all i have tested so far)
2. Try and move it around your inventory

### OS and Versions

* PocketMine-MP: 4.2.0
* PiggyCustomEnchants: Dev build #487
* PHP: 8
* Server OS: Linix

### Extra Information

**Comment by Sly-Zipy** [comment]
do you have virions for this plugin? 
i need virions spare part for this plugin

**Comment by ErosionYT** [comment]
u dont need virions for this plugins?
