### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GamerMJay** [DaPigGuy/PiggyCustomEnchants#388]
Hey, is this Normal??
![168092652-15bc52ad-253f-4384-84a0-d4fdd2adc678](https://user-images.githubusercontent.com/66413999/169668958-86880b5b-8775-4cc8-9e95-f679f7fc0404.gif)

**Comment by DaPigGuy** [comment]
Yes

**Comment by GamerMJay** [comment]
oh okay, then unfortunately I can no longer use the plugin because it is then too OP.. Thanks for the quick answer anyway

**Comment by GamerMJay** [comment]
short question can you do it in such a way that you can activate and deactivate it?
