### ISSUE TITLE
Bug (followed guidelines)

### ISSUE THREAD

**Issue by QuiverlyRivalry** [DaPigGuy/PiggyCustomEnchants#40]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**
 Server trys to start plugin but then crashes saying this ErrorException: "Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::getEnchantment(int $id) should be compatible with pocketmine\item\enchantment\Enchantment::getEnchantment($id)" (EXCEPTION) in "PiggyCustomEnchants.phar/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants" at line 136
06.09 19:55:36 [Server] Server thread/CRITICAL Could not load plugin 'PiggyCustomEnchants'

#### **Version of PiggyCustomEnchants:**
 latest from github 9/6/2017

#### **Data Provider:**

- [1 ] MySQL
- [ 1] SQLite
- [ 1] YAML
- [ 1] JSON

#### **Steps to Reproduce the Issue**

1. Start server (latest pmmp)

#### **Extra Information**

Well I am using API 3.0.0 APLHA 7

**Comment by DaPigGuy** [comment]
Outdated PocketMine.
