### ISSUE TITLE
Item Meta

### ISSUE THREAD

**Issue by JustYuss** [DaPigGuy/PiggyCustomEnchants#402]
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PiggyCustomEnchants

Error: Item meta must be in range 0 ... 32767 (received -999)
File: pmsrc/src/network/mcpe/convert/TypeConverter
Line: 253
Type: pocketmine\network\mcpe\convert\TypeConversionException
Backtrace:
#0 plugins/PiggyCustomEnchants (1).phar/src/DaPigGuy/PiggyCustomEnchants/utils/Utils(203): pocketmine\network\mcpe\convert\TypeConverter->netItemStackToCore(object pocketmine\network\mcpe\protocol\types\inventory\ItemStack#630143)
#1 plugins/PiggyCustomEnchants (1).phar/src/DaPigGuy/PiggyCustomEnchants/EventListener(77): DaPigGuy\PiggyCustomEnchants\utils\Utils::filterDisplayedEnchants(object pocketmine\network\mcpe\protocol\types\inventory\ItemStack#630143)
#2 pmsrc/src/event/RegisteredListener(60): DaPigGuy\PiggyCustomEnchants\EventListener->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#621633)
#3 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#621633)
#4 pmsrc/src/network/mcpe/NetworkSession(408): pocketmine\event\Event->call()
#5 pmsrc/src/network/mcpe/NetworkSession(372): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#404458, string[686] ...............................Damage.......chargedItem...Countc...Damage.....Na)
#6 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[309] [.*..(....4...............F...f6......T.?..sq3$g$....x...2.28....$3...b.`a.K.M.g)
#7 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 136, string[318] .%... .E ..l..k...x....k...=....?I...x.....:..5..1.6..V..B.......L.. ....j...+..)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#26948)
#9 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#11 pmsrc/src/Server(1707): pocketmine\snooze\SleeperHandler->sleepUntil(float 1666181337.7433)
#12 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
#13 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#14 pmsrc/src/PocketMine(328): pocketmine\server()
#15 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[244] 			}
[245] 			if($compound->count() === 0){
[246] 				$compound = null;
[247] 			}
[248] 		}
[249] 		if($id < -0x8000 || $id >= 0x7fff){
[250] 			throw new TypeConversionException("Item ID must be in range " . -0x8000 . " ... " . 0x7fff . " (received $id)");
[251] 		}
[252] 		if($meta < 0 || $meta >= 0x7fff){ //this meta value may have been restored from the NBT
[253] 			throw new TypeConversionException("Item meta must be in range 0 ... " . 0x7fff . " (received $meta)");
[254] 		}
[255] 
[256] 		try{
[257] 			return ItemFactory::getInstance()->get(
[258] 				$id,
[259] 				$meta,
[260] 				$itemStack->getCount(),
[261] 				$compound
[262] 			);
[263] 		}catch(NbtException $e){

**Comment by Aericio** [comment]
I think these errors were removed in PM5, since I can't find it in the code anymore. Linking to a related netItemStackToCore issue instead -> #425
