### ISSUE TITLE
New Custom Enchanted

### ISSUE THREAD

**Issue by AffanStarPure** [DaPigGuy/PiggyCustomEnchants#41]
Suggestions Custom Enchanted New

Armored
Decreases damage from your opponents swords by 2% per level

Tank
Decreases damage from your opponents axes by 2% per level

Heavy
Decreases damage from enemy bows by 2% per level

Is possible add new custom Enchanted? I just suggestions i hope u add @DaPigGuy  because this for protection decrease damage on armor equip

**Comment by DaPigGuy** [comment]
This has been added to the todo list.
