### ISSUE TITLE
Creating a new rarity

### ISSUE THREAD

**Issue by EmporiumPvP** [DaPigGuy/PiggyCustomEnchants#411]
i tried joining your discord it says cannot accept invite 
![Screenshot 2023-03-08 213711](https://user-images.githubusercontent.com/89197165/223855964-dcadf0ca-e019-4de8-b1ef-590269ac9c09.png)

I am trying to create a new enchant rarity but when ever i load the server i get the error "Undefined array key "Pickaxeultimate"" (EXCEPTION)

**Comment by Aericio** [comment]
We don't support custom modifications of PiggyCustomEnchants.
