### ISSUE TITLE
Item swapped

### ISSUE THREAD

**Issue by Studgi** [DaPigGuy/PiggyCustomEnchants#423]
### Issue Description

- Expected result: I would be given the correct items or the items I have in my inventory would be correctly what I had before I updated pocketmine 
- Actual result: When I did /give name ender_chest, it gave me magenta concrete. It swaps items like that for other items as well like obsidian, bedrock etc

#### Steps to Reproduce the Issue
1. /give <name> ender_chest

### OS and Versions

* PocketMine-MP: PM 5.6.0
* PiggyCustomEnchants: 3.1.0
* PHP: 8.2
* Server OS: Ubuntu

### Extra Information

I disabled all other plugins so I am almost certain this is not caused by any of my plugins. I disabled PiggyCustomEnchants and the bug disappeared.

![image](https://github.com/DaPigGuy/PiggyCustomEnchants/assets/80104967/5485e9c8-38a9-4ed5-b192-6a0668ba6dce)

**Comment by Aericio** [comment]
We're going to have to use Customies for our enchantment books. I suppose that's the problem.
