### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by ivigb** [DaPigGuy/PiggyCustomEnchants#428]
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of jojoe77777\FormAPI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/AlmasssDeathh.phar/src/jojoe77777/FormAPI/Form.php:54
Stack trace:
#0 phar:///home/container/plugins/AlmasssDeathh.phar/src/jojoe77777/FormAPI/Form.php(10): pocketmine\utils\Utils::errorExceptionHandler(8192, 'Return type of ...', 'phar:///home/co...', 54)
#1 phar:///home/container/BetterAltay.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(138): include('phar:///home/co...')
#2 phar:///home/container/BetterAltay.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(124): BaseClassLoader->loadClass('jojoe77777\\Form...')
#3 [internal function]: BaseClassLoader->{closure}('jojoe77777\\Form...')
#4 /home/container/plugins/PiggyCustomEnchants-1393076ef349c6741ac03ee8bd6a60715a4eb919/src/DaPigGuy/PiggyCustomEnchants/PiggyCustomEnchants.php(47): class_exists('jojoe77777\\Form...')
#5 phar:///home/container/BetterAltay.phar/src/pocketmine/plugin/PluginBase.php(119): DaPigGuy\PiggyCustomEnchants\PiggyCustomEnchants->onEnable()
#6 phar:///home/container/BetterAltay.phar/src/pocketmine/plugin/PluginManager.php(559): pocketmine\plugin\PluginBase->setEnabled(true)
#7 phar:///home/container/BetterAltay.phar/src/pocketmine/Server.php(1941): pocketmine\plugin\PluginManager->enablePlugin(Object(DaPigGuy\PiggyCustomEnchants\PiggyCustomEnchants))
#8 phar:///home/container/BetterAltay.phar/src/pocketmine/Server.php(1927): pocketmine\Server->enablePlugin(Object(DaPigGuy\PiggyCustomEnchants\PiggyCustomEnchants))
#9 phar:///home/container/BetterAltay.phar/src/pocketmine/Server.php(1728): pocketmine\Server->enablePlugins(1)
#10 phar:///home/container/BetterAltay.phar/src/pocketmine/PocketMine.php(333): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), '/home/container...', '/home/container...')
#11 phar:///home/container/BetterAltay.phar/src/pocketmine/PocketMine.php(363): pocketmine\server()
#12 /home/container/BetterAltay.phar(11): require('phar:///home/co...')
#13 {main} in phar:///home/container/plugins/AlmasssDeathh.phar/src/jojoe77777/FormAPI/Form.php on line 10
19:22:57 Server|EMERGENCY > An unrecoverable error has occurred and the server has crashed. Creating a crash dump
19:22:57 Server|EMERGENCY > Please upload the "/home/container/crashdumps/Mon_Dec_11-19.22.57-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
19:22:57 Server|EMERGENCY > Automatic crash report submission failed: Only crash reports from PocketMine-MP are accepted

**Comment by nicholass003** [comment]
it caused by outdated FormAPI from plugin 'AlmasssDeathh'
