### ISSUE TITLE
conflict appears to be caused by PiggyCustomEnchants being installed with PureEntitiesX

### ISSUE THREAD

**Issue by teracube** [DaPigGuy/PiggyCustomEnchants#46]
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [x] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title like "CustomEnchants::getName() must be..."
- * [x] Provide any crash dumps or errors

#### **General**

conflict appears to be caused by PiggyCustomEnchants being installed with PureEntitiesX

#### **Version of PiggyCustomEnchants:**
https://poggit.pmmp.io/r/11407/PiggyCustomEnchants_dev-77.phar

#### **Data Provider:**
PocketMine-MP version: 1.7dev #98 [Protocol 137; API 3.0.0-ALPHA8]
CEST 2016 x86_64
PHP Version: 7.2.0RC1
Zend version: 3.2.0-dev
OS : Linux,

#### **Steps to Reproduce the Issue**
Install
https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.7dev-98_90cb018d_API-3.0.0-ALPHA8.phar

https://poggit.pmmp.io/r/11407/PiggyCustomEnchants_dev-77.phar
//API Alpha 8 updated with PocketMine Tools on line//

https://poggit.pmmp.io/r/12628/PureEntitiesX_dev-118.phar

#### **Extra Information**
PureEntities issue:
https://github.com/RevivalPMMP/PureEntitiesX/issues/222

Server log
[server.log](https://github.com/DaPigGuy/PiggyCustomEnchants/files/1335072/server.log)

**Comment by Aericio** [comment]
PiggyCustomEnchants does __not__ support ALPHA8. Unless you know what to update along with the API, you should not manually change the api.
