### ISSUE TITLE
I Can Help Update To ALPHA8

### ISSUE THREAD

**Issue by PotatoeTrainYT** [DaPigGuy/PiggyCustomEnchants#47]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

Hey, Ive Seen Your Not Updating To ALPHA8, Ive Fixed The Plugin And Made It Work On ALPHA8 I Was Wondering If You Could Allow Me To Contribute With This Plugin And Update It!
#### **Data Provider:**

- [ ] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Discord - Potatoe#4738

**Comment by QuiverlyRivalry** [comment]
Fork it apply changes then PR it

**Comment by optimusprime338** [comment]
potato is a troll dude and does nothing but mess!!

**Comment by QuiverlyRivalry** [comment]
Lol optimus

**Comment by Aericio** [comment]
https://github.com/PotatoeTrainYT/PiggyCustomEnchants/commit/de81dee95785842ebca87fcbc95c0ce6c01397cf
Commit does NOT make the necessary changes to fully support ALPHA8. Denied.
