### ISSUE TITLE
Kit plugin for customenchants

### ISSUE THREAD

**Issue by VoliPlays** [DaPigGuy/PiggyCustomEnchants#48]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **Data Provider:**

- [ ] MySQL
- [ ] SQLite
- [ ] YAML
- [ ] JSON

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**

Can you do a kit plugin which supports custom enchants?

**Comment by DaPigGuy** [comment]
https://github.com/poggit-orphanage/AdvancedKits
