### ISSUE TITLE
Enchant colour?

### ISSUE THREAD

**Issue by Dragonblitz10** [DaPigGuy/PiggyCustomEnchants#6]
Legendary Orange/gold
Elite: Aqua or Blue
Ultimate: Yellow
Simple: White 

Different colours for diffrent enchant or the ability to chose the colour

http://imgur.com/a/orU50 (Coloured)

**Comment by MCPEPIG** [comment]
Probably not now.

**Comment by akaSnapy** [comment]
You can build them easy
$lvl = $ench->getLevel();
       if($lvl == 1) {
        $level = "I";
           }
       if($lvl == 2) {
        $level = "II";
           }
       if($lvl == 3) {
        $level = "III";
           }
       if($lvl == 4) {
        $level = "IV";
           }
       if($lvl == 5) {
        $level = "V";
           }
	if($item->getId() == 276) {
		if($ench->getId() == 30) {
			$p->sendPopup(C::AQUA . "Diamond Sword\n§4Oink §7LifeSteal $level");

**Comment by MCPEPIG** [comment]
Ewww, no...

**Comment by MCPEPIG** [comment]
That's a mess.

**Comment by akaSnapy** [comment]
I tested it and works fine ;)

**Comment by MCPEPIG** [comment]
You want me to do that for EVERY enchant? Are you mad?

**Comment by MCPEPIG** [comment]
I have a better method...

**Comment by DaPigGuy** [comment]
Test this out: e91310f22a7994dbb363dc69ab127e9971c8b187

**Comment by Aericio** [comment]
Test the latest commit (https://github.com/DaPigGuy/PiggyCustomEnchants/commit/2eff7c5e62ce5b0ee5f55fd5c22764d0c1dd45ce). If everything works, I'll close this issue.
