### ISSUE TITLE
Unable to enchant item

### ISSUE THREAD

**Issue by jaydeboer** [DaPigGuy/PiggyCustomEnchants#63]
#### **General**
I am new to PMMP so it is likely that I just don't have some common knowledge on how to use plugins.  My son and I are trying to figure out how to apply these enchants to items in the game.  If we type ```/customenchant``` we get the response of ``` /customenchant <enchant:list> ```.  Is it possible to apply enchants with a /command?  If so, what is the format?

#### **Version of PiggyCustomEnchants:**
v1.0.4

**Comment by jaydeboer** [comment]
Never mind.  We've been working on this for an hour, then 7 minutes after we ask for help, we figure it out. Sorry for the noise.

**Comment by Aericio** [comment]
No problem. Feel free to ask if you have any other issues, we'd be glad to help :)
