### ISSUE TITLE
Icon Needed!

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyCustomEnchants#65]
Hullo! =)

I need an icon for PiggyCustomEnchants. Check requirements below. If you would like to make one, send it to me on the PMMP forums, or on Discord (DaPigGuy#4580). The best one will be used and you will receive credit. 

**Requirements**
* Must show a pig
* Must show enchantments (Enchanted Sword, Enchanted Book, Enchantment Table, Enchanted Pig, etc.)
* Appropriate

Thank you,
Pig

**Comment by Aericio** [comment]
@GatorThePlayer :3

**Comment by Aericio** [comment]
https://github.com/DaPigGuy/PiggyCustomEnchants/commit/b0c300210445e506eb646b8af823d1f31bc9fda4
