### ISSUE TITLE
Magmawalker doesn't work on lava placed with buckets

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyCustomEnchants#66]
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [x] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title like "CustomEnchants::getName() must be..."
- * [x] Provide any crash dumps or errors

#### **General**

When lava is set with World Edit, the Magmawalker enchant works fine. However, when lava from a bucket is placed, it does not function.

#### **Version of PiggyCustomEnchants:**

1.0.5 build 103

#### **Steps to Reproduce the Issue**

1. Use lava buckets
2. Equip Magmawalker boots

**Comment by DaPigGuy** [comment]
Have to do a bit more testing tomorrow

**Comment by QuiverlyRivalry** [comment]
Whyd you open an issue on your own plugin? Lol

**Comment by Aericio** [comment]
@QuiverlyRivalry so people are aware of the issue.
