### ISSUE TITLE
Meditation won't apply.

### ISSUE THREAD

**Issue by DarkIceTitan** [DaPigGuy/PiggyCustomEnchants#68]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

When I try to apply meditation to a helmet it says that the enchant is not compatible with that item.
#### **Version of PiggyCustomEnchants:**

1.0.5
#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Fixed.

**Comment by DarkIceTitan** [comment]
Thank you!
