### ISSUE TITLE
problem with enchants like glowing and gears etc.

### ISSUE THREAD

**Issue by timbersquirrel** [DaPigGuy/PiggyCustomEnchants#70]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

I cant keep enchants active like glowing gears and springs when being hit by a mob or player etc.
*I am using the latest version of pmmp*
#### **Version of PiggyCustomEnchants:**

PiggyCustomEnchants version 1.0.5
#### **Steps to Reproduce the Issue**

1. Enchant youre helmet with glowing
2. Have a player or mob hit you
3. The night vision wears off instantly and you loose the effects from it untill you re-equip it
#### **Extra Information**

Please try to get it fixed

**Comment by AffanStarPure** [comment]
Yes i have same issue when equip Armor With glowing on helmet on Durability work take off effect too when take damage even autorepair too when repair u armor Glowing with Autorepair loose effect too need fix too only on armor duralibity

**Comment by QuiverlyRivalry** [comment]
wha @AffanStarPure

**Comment by DaPigGuy** [comment]
I can't reproduce this issue.

**Comment by timbersquirrel** [comment]
I’m using version: PocketMine-MP 1.7dev-406 「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.0.81 (protocol version 137) i don’t know if you are using a different version

**Comment by Aericio** [comment]
Can you use the latest version of pmmp? (18 builds have passed, maybe something changed ¯\(ツ)/¯)
Here's the link to Jenkins: https://jenkins.pmmp.io/job/PocketMine-MP/

**Comment by timbersquirrel** [comment]
That didn’t fix it but it needs to be fixed

**Comment by AffanStarPure** [comment]
https://youtu.be/WItkPYPif_I watch my video they bug is not problem version PMMP i show proof

**Comment by DaPigGuy** [comment]
I can't reproduce with the steps given by the issue and your video isn't clear enough.

**Comment by timbersquirrel** [comment]
What version of pmmp are you using @dapigguy

**Comment by DaPigGuy** [comment]
Commit 88ad43971ad51b87d566cbed090d4e769028ce95

**Comment by DaPigGuy** [comment]
@timbersquirrel Are you currently available?

**Comment by timbersquirrel** [comment]
I just downloaded that too but mine will remove the effect upon damage :/

**Comment by DaPigGuy** [comment]
Are you available?

**Comment by DaPigGuy** [comment]
On @AffanStarPure's server to investigate

**Comment by timbersquirrel** [comment]
Ok thanks dude

**Comment by timbersquirrel** [comment]
@dapigguy 
I just downloaded the recent version of pce 
Glowing makes the sky flash 
Also springs is a bit glitchy maybe revert it back to jump boost

**Comment by DaPigGuy** [comment]
@timbersquirrel The issue with glowing is not our problem.

**Comment by DaPigGuy** [comment]
Fixed sky flashing. Please be more specific about whats wrong with springs and create another issue.

**Comment by timbersquirrel** [comment]
Ok
