### ISSUE TITLE
Volley Enchant Can Be Used To Duplicate

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#74]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

Shuffle use 1 arrow and spawn 4 . It allow players to duplicate arrows
#### **Steps to Reproduce the Issue**

1. Use shuffle enchant and shoot

#### **Extra Information**

Shuffle should use 4 arrows instead of 1

**Comment by DaPigGuy** [comment]
The enchant you are talking about is Volley and not Shuffle.

**Comment by TDMidkwhatisxd** [comment]
my bad ^^
