### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by timbersquirrel** [DaPigGuy/PiggyCustomEnchants#75]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

Any custom enchant like gears and glowing that give infinite effects will keep turning on and off
#### **Steps to Reproduce the Issue**

1. /time set night
2. /ce enchant glowing
3. Look at sky
4. It flashes

#### **Extra Information**

Maybe revert springs back to jump boost because it is glitchy with it set the way it is

**Comment by akaSnapy** [comment]
Thats not a issue

**Comment by DaPigGuy** [comment]
This issue was just fixed 🤦‍♂️
