### ISSUE TITLE
Chance

### ISSUE THREAD

**Issue by isoz** [DaPigGuy/PiggyCustomEnchants#76]
You should make the enchants have a chance of activating instead of being instant, it's extremely unbalanced.

**Comment by coolkidsrule101** [comment]
yeah that cool to have a rate  chance for the enchantment to work. add dust to increase the chance of sucess in config and php

**Comment by coolkidsrule101** [comment]
such as sugar or glowstone dust

**Comment by jrodr10** [comment]
make this feature disableable as its pointless for a factions server but may not be for a vanilla server or minigames server

**Comment by DevCreationAI** [comment]
Basically add chances for Enchantments that break the item but also have it where it can be disabled with a config option.

**Comment by PotatoeTrainYT** [comment]
books would come before this request im guessing, but pig has a big to do list so it won't be an update coming soon https://github.com/DaPigGuy/PiggyCustomEnchants/issues/2

**Comment by QuiverlyRivalry** [comment]
Well, as far as I know priorities are high for books, then implementing /combine.
As far balancing, I am starting it as a PR, if you know any OP enchant just comment on the PR

**Comment by TDMidkwhatisxd** [comment]
Great idea .... Enchants should have 50% chances to activate (by default in config)

**Comment by QuiverlyRivalry** [comment]
@DaPigGuy would this be added, before I balance, or after?

**Comment by DaPigGuy** [comment]
This will be worked on by Aericio and I.

**Comment by TDMidkwhatisxd** [comment]
i added  chance on my server , only on effects made by armours (not souldbound etc.. xd)

**Comment by coolkidsrule101** [comment]
Cool

**Comment by Benjiboi6578** [comment]
/combiner and /tinkerer would be nice. I known that will take a while. But I was wondering if implementing xp way of earning books is possible? Like by grinding.

**Comment by coolkidsrule101** [comment]
How did you add chance

On Dec 14, 2017 9:48 PM, "Benjiboi6578" <notifications@github.com> wrote:

/combiner and /tinkerer would be nice. I known that will take a while. But
I was wondering if implementing xp way of earning books is possible? Like
by grinding.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DaPigGuy/PiggyCustomEnchants/issues/76#issuecomment-351898568>,
or mute the thread

**Comment by Aericio** [comment]
@Benjiboi6578 Do you mean grinding for xp and using an enchantment table (sign, gui, whatever) to get the custom enchant, or by chances of dropping from mobs?

**Comment by PotatoeTrainYT** [comment]
i think chances to activate the enchant

**Comment by PotatoeTrainYT** [comment]
oh i think for the books idk

**Comment by DaPigGuy** [comment]
0084e96
