### ISSUE TITLE
Enchants Entire Stack

### ISSUE THREAD

**Issue by Haxley** [DaPigGuy/PiggyCustomEnchants#77]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

You can enchant stacks. It really only matters for Radar (Compass) and even only then if you sell custom enchants, say via a CommandShop. 

#### **Version of PiggyCustomEnchants:**

1.0.6

#### **Steps to Reproduce the Issue**

1. "/ce enchant radar" on a stack of Compasses 

#### **Extra Information**

I don't think so.

**Comment by Aericio** [comment]
> even only then if you sell custom enchants, say via a CommandShop.

wat?

**Comment by Haxley** [comment]
I mean this really isn't a problem unless custom enchants are part of your economy.

**Comment by Haxley** [comment]
Awesome, thanks!
