### ISSUE TITLE
Info Subcommand

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [DaPigGuy/PiggyCustomEnchants#79]
Could you add command /ce info, ex (when u hold enchant info wat?)

**Comment by PotatoeTrainYT** [comment]
@xXNiceAssasinl0 Your In Luck! Me And Pig Are Working On /ce info!

**Comment by DaPigGuy** [comment]
Taken over now LUL.

**Comment by DaPigGuy** [comment]
bb273cc9b8991cf67dd320bde1cc0134e051c32c

**Comment by xXNiceAssasinl0** [comment]
Abcdefghijklmnopqrstuvwxyz

**Comment by QuiverlyRivalry** [comment]
Translation of @xXNiceAssasinl0 : 
THANKS PIGGY, YOU THE BEST, I LOVE YOU, I LOVE BEEF, BACON IS BAE, ME NEVER EAT BACON LONG LIVE PIG

**Comment by xXNiceAssasinl0** [comment]
Your Wrong @QuiverlyRivalry xD

**Comment by xXNiceAssasinl0** [comment]
My teacher tech me that
