### ISSUE TITLE
Lightning

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [DaPigGuy/PiggyCustomEnchants#80]
Would be great if u add lightning enchant,

**Comment by DarkIceTitan** [comment]
Suggest custom enchantments on the google forms.

**Comment by DaPigGuy** [comment]
Like @DarkIceTitan said, please submit ideas on the Google Forms (here)[https://docs.google.com/forms/d/e/1FAIpQLScfWdk8OyQ6NNw6KiJxP_4CH4GHnKlaFr4VfZIQojk7OPlyoQ/viewform]
