### ISSUE TITLE
enchant ids?

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [DaPigGuy/PiggyCustomEnchants#82]
can i use these as enchant ids https://github.com/DaPigGuy/PiggyCustomEnchants/blob/master/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants.php#L13

**Comment by PotatoeTrainYT** [comment]
you can use them as another way of enchanting, so '/ce enchant 117' would add Disarming to your sword

**Comment by QuiverlyRivalry** [comment]
i never knew ces were ids 👯

**Comment by XoticRealmsOwnerandDev** [comment]
thanks

**Comment by PotatoeTrainYT** [comment]
no problem!
