### ISSUE TITLE
enchants glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#85]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

PLayers gets unlimited golden hearts
#### **Steps to Reproduce the Issue**

1. Use these enchants  
  - "276:0:1:Cursed Sword:lifesteal:2:deathbringer:5"
  - "310:0:1:DEFAULT:berserker:2:glowing:1"
  - "311:0:1:DEFAULT:revulsion:2:enlighted:2"
  - "312:0:1:DEFAULT:poisoned:3:hardened:1"
  - "313:0:1:DEFAULT:frozen:2"
2. Get hit by a wooden sword

#### **Extra Information**

Hi, players where reporting that they gets unlimited golden heartz if they got hit by wooden/stone swords.

**Comment by DaPigGuy** [comment]
This is unusual, can you list your plugins?

**Comment by TDMidkwhatisxd** [comment]
AntiSpamPro v1.4.0-2, iProtector v3.1.0-3, NoTell v1.1.2-2, superBAR v1.6.5-1, KitUI v1.1.3, DevTools v1.12.6, ProfileUI v4.1.0, AlwaysSpawn v2.2.3-3, KeepInventory v1.0.2, AllAPILoader v1.0.0, Slapper v1.3.7, ClearLagg v1.1.0, PiggyCustomEnchants v1.0.7, essentialsTP v1.2.0-1.alpha8, Parkour v1.5.6-3, PlayerVaults v2, TimeCommander v2.1-ALPHA8, HydraStart v1.0.0, MyPlot v1.1.7-pre, WorldProtect v2.3.5-1.alpha8, KillChat v1.0.2.MOD, PurePerms v1.4.1-1.alpha8, VoteReward v3.0.2-1.alpha8, EconomyAPI v5.7.1-2.alpha8, EconomySell v2.0.7-1.alpha8, MagicTelePortal v1.3.2-1.alpha8, EconomyShop v2.0.8-1.alpha8, FactionsPro v1.3.11-2.alpha8, PureChat v1.4.10-2.alpha8

**Comment by TDMidkwhatisxd** [comment]
I noticed, wen ppl are hitting me I get 3-4 extra  hearts sometimes...
Is there a code that give players extra hearts?(I deleted plugins list , because I don't wanna be accesed by anyone, I think u got the list in email)

**Comment by DaPigGuy** [comment]
The only enchant that gives extra health is Overload (wear to get)

**Comment by TDMidkwhatisxd** [comment]
not using overload enchants .... But cant anyone else reproduce this issue?

**Comment by TDMidkwhatisxd** [comment]
I wonder if can be lifesteal enchant ... Ill test

**Comment by PotatoeTrainYT** [comment]
i doubt lifesteal would give u more than ur normal health

**Comment by TDMidkwhatisxd** [comment]
poison+lifesteal may do it...

**Comment by TDMidkwhatisxd** [comment]
https://youtu.be/hJdSl32NIgQ

It seems I didn't need to use sword to reproduce the glitch.... And player sword was a lifesteal sword ... or a lifesteal + deathbringer V sword.

The glitch is for a long time so I don't think sword enchant matters.

**Comment by TDMidkwhatisxd** [comment]
I think plugin should check if enchant exist first
And if no it should apply ... Even if u get hit again effect should not be applied again.
I think if u hit someone fast, effect spam and glitch...

**Comment by PotatoeTrainYT** [comment]
soon chances are being added to the enchants, would chances (like 10% chance to activate ability) fix this issue do you think?

**Comment by TDMidkwhatisxd** [comment]
I think, checking if a player got effect, is much more effective. But anyway, I will wait ^^

**Comment by TDMidkwhatisxd** [comment]
it seems that changes will take a while... Not to say , spamming /effect because of player hit, may cause performance issue.
I will mod the plugin for me, I wish u good luck and hope that my issue helps.

**Comment by TDMidkwhatisxd** [comment]
It works, I have no problems anymore . After entity damage by event I put rand(1,7) and if rand = 5 let the magic run.
I noticed that tasks eat performance a lot... Is just me?

https://timings.pmmp.io/?url=26113514

**Comment by PotatoeTrainYT** [comment]
thats exactly what i said, after we add chances it will be fixed, what you done id added chances

**Comment by TDMidkwhatisxd** [comment]
Nope its not, ppl still get extra heartz, just that it cant get spammed to make 100 heartz anymore.
I think my idea to check if enchants are on before apply is better.

**Comment by TDMidkwhatisxd** [comment]
I did a test ... it seems that if u hit a player with regeneration many times, u spam regeneration effect on him and it can become a gitch .... Making more heartz .... But  I still don't know ....

After I added chances to effect , it happen rarely ....

**Comment by jrodr10** [comment]
When i first started reading your comments i thought you were dumb or a child or both... but now that i read them all you kinda have a point @TDMidkwhatisxd , though i do not think that adding a chance should be added to all the enchants, sure Lifesteal should prob be by chance but other enchants like Soulbound should not.

**Comment by DaPigGuy** [comment]
@TDMidkwhatisxd If regeneration is what's causing it, it's not our issue. It's an issue with PMMP that only gets caused by PiggyCE.

**Comment by DarkIceTitan** [comment]
This problem with the golden hearts happens even without custom enchantments. This isn't a glitch or bug with PiggyCE.

**Comment by Aericio** [comment]
Will mark as wontfix for now, since it seems that the issue is caused by PMMP.

**Comment by TDMidkwhatisxd** [comment]
Yah , enchants like soulbound should not have chance... I mean enchants , that give harmful/good effect should have chance, because with every hit effects are spammed.

**Comment by TDMidkwhatisxd** [comment]
Is not caused by pmmp ... but anyway ...

**Comment by Aericio** [comment]
It'll be re-opened if proven otherwise, but currently it seems like it's a pmmp bug.
