### ISSUE TITLE
Vanilla Enchnats

### ISSUE THREAD

**Issue by optimusprime338** [DaPigGuy/PiggyCustomEnchants#88]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

The Plugins like TeaSpoon by @CortexPE and VanillaEnchantments by @TheAz928 are not able to register enchants whenever I load this plugin!! Talked on of there contributer said its PCE fault :- "the damage hander there tries stuff that is invalid"! Please Fix it is possible.. TY

#### **Steps to Reproduce the Issue**

1.

**Comment by QuiverlyRivalry** [comment]
@DaPigGuy same here. That plugin the vanilla enchants, one. Is a essential plugin like yours. It'd be cool if you add suport too it or make your own 0.o

**Comment by DaPigGuy** [comment]
@optimusprime338 I've tested this plugin with the latest version of PiggyCE. Both plugins work as intended. Please try with the latest version. If this doesn't fix the issue, open another issue with specific details about what's wrong.
