### ISSUE TITLE
"Pigs dont like spoons so enjoy a featureless custom enchants..."

### ISSUE THREAD

**Issue by Benjiboi6578** [DaPigGuy/PiggyCustomEnchants#89]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

I run a virtual gladiator server. The plugin is installed and I can do /version PiggyCustomEnchants so I know I'm running it but I cant do /ce. It says that it doesn't exist. So what is the problem. is it because I'm running spoon. I was able to get it running before when it said that I was running spoon. so why all of a sudden is it that I cant get /ce. Is there a way to get rid of the spoon thing? or do I have to enable the default to allow the plugin. But when look in my plugins folder I don't see the PiggyCustomEnchant folder, I just see the phar file. Why is that?
#### **Steps to Reproduce the Issue**

1.

**Comment by DaPigGuy** [comment]
Well, maybe if you actually read it, you'd know.

**Comment by Aericio** [comment]
You are not running PMMP, or if you are, you may be running an unofficial version of PMMP.
