### ISSUE TITLE
Vanilla Enchantments

### ISSUE THREAD

**Issue by optimusprime338** [DaPigGuy/PiggyCustomEnchants#90]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

Having PiggycustomEnchnats plugins:-
![image](https://user-images.githubusercontent.com/27479208/33660900-990dc394-daab-11e7-8c1f-1e2aac84e582.png)
Without PGCE:-
![image](https://user-images.githubusercontent.com/27479208/33660926-b7757ad4-daab-11e7-8f42-c179dabc50b1.png)
#### **Version of PiggyCustomEnchants:**

Commit:- 512518a, Dev #152, version:- 1.0.8

#### **Steps to Reproduce the Issue**

1.

**Comment by optimusprime338** [comment]
nvm works with vanilla enchants dont know why not working with TeaSpoon!!

**Comment by DaPigGuy** [comment]
TeaSpoon is extremely buggy.

**Comment by PotatoeTrainYT** [comment]
TeaSpoon enchants don't work fully yet

**Comment by optimusprime338** [comment]
Almost enchants are added in latest updates

**Comment by Aericio** [comment]
https://twitter.com/dktapps/status/933630103535448064

uninstall teaspoon.

**Comment by optimusprime338** [comment]
Yh ty!!
