### ISSUE TITLE
JetPack big glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#91]
Please make sure your issue complies with these guidelines:
- * [ ] Be using PMMP
- * [ ] Make sure the issue hasn't already been reported
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title like "CustomEnchants::getName() must be..."
- * [ ] Provide any crash dumps or errors

#### **General**

If you enter in portal with jetpack on .... you can use it on blocked worlds .......
Is bad, now players can cheat on parkour
#### **Steps to Reproduce the Issue**

1.

**Comment by PotatoeTrainYT** [comment]
this isnt the plugins fault, why don't you make a plugin to check of they are wearing armor in that world and if they are make them get teleported to spawn

**Comment by TDMidkwhatisxd** [comment]
I was gotta making right now

**Comment by TDMidkwhatisxd** [comment]
U know u can cancel ppl teleporting to other worlds if jetpack on? Well, ya we not so pro devs...

**Comment by TDMidkwhatisxd** [comment]
Because of that I need to whitelist sv and fix as fast as I can

**Comment by TDMidkwhatisxd** [comment]
I fixed for me, I made it so it check if u are flying and the world, if not right world fly is canceled ... Works like a charm, Ill reopen this because is a easy fix + I made so that it counts worlds from config not another file.... Just 4 lines of code ... Ik u can do it.
