### ISSUE TITLE
too many tasks

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#92]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **General**

http://timings.pmmp.io/?url=26140371
:3

#### **Steps to Reproduce the Issue**

1.

**Comment by PotatoeTrainYT** [comment]
all the tasks used are needed for the enchants to work so i dont get why you say there's too many

**Comment by Aericio** [comment]
I don't see any issue here, you can have them split into different tasks for organization or have them grouped up into one file... they'd still have the same percentages.

**Comment by TDMidkwhatisxd** [comment]
there is no discord sv

**Comment by Aericio** [comment]
https://discordapp.com/invite/ZZewRQH
