### ISSUE TITLE
Rename Custom Enchant(Auto Repair)

### ISSUE THREAD

**Issue by Darkkz** [DaPigGuy/PiggyCustomEnchants#97]
Hello Piggy, I was wondering if you could the  enchants name called Auto Repair to Hellforged. It sounds a whole lot better I think. Please do this it would make my day

**Comment by Darkkz** [comment]
will you please do it

**Comment by PotatoeTrainYT** [comment]
why tho... hellforged doesn't fit what it does

**Comment by QuiverlyRivalry** [comment]
Fork it and do it your self, remember pigs are lazy

**Comment by Aericio** [comment]
"Forged" would refer to a creation, wouldn't it? I agree with @PotatoeTrainYT, repair doesn't fit in with forged. Our license allows modification for private use (as long as author is not changed), so you may modify that for your own server. I consider that this should not be modified @DaPigGuy.

**Comment by DaPigGuy** [comment]
I'd have to agree with @Aericio & @PotatoeTrainYT. If you'd like to change it, you can fork the plugin.
