### ISSUE TITLE
effect spam

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [DaPigGuy/PiggyCustomEnchants#98]
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [ ] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [ ] If possible, provide crashdumps/errors related to the issue.

#### **Steps to Reproduce the Issue**

1.

#### **Extra Information**
<!-- Anything else we should know? 
effect should be check before apply

**Comment by DaPigGuy** [comment]
Please fill the template.

**Comment by TDMidkwhatisxd** [comment]
sorry about that I was confused too....
I added check for every effects, if player got effect , he wont get effect again until it is gone.

I added this in my server and fixed a little performance + bye golden heartz spam.
Tested

If you wanna my event file invite me to discord. If not maybe u know better how to do.

**Comment by TDMidkwhatisxd** [comment]
as u wish, forget about it :/

**Comment by TDMidkwhatisxd** [comment]
nice pig , is same as I did .
